// 甜甜导航 - 站点数据（自动生成）
export interface Site {
  id: string;
  name: string;
  url: string;
  desc: string;
  icon?: string;
}

export const categories_part3: Record<string, Site[]> = {
  "UI资源": [
    { id: "9", name: "UI中国", url: "http://www.ui.cn", desc: "UI设计垂直社区" },
    { id: "240", name: "UI自用导航", url: "http://dh.simple.red", desc: "UI自用导航UI设计资源" },
    { id: "80", name: "稀土区", url: "https://xituqu.com", desc: "稀土区UI设计资源" },
    { id: "79", name: "Designmodo", url: "https://designmodo.com", desc: "DesignmodoUI设计资源" },
    { id: "76", name: "Freebiesbug", url: "https://freebiesbug.com", desc: "FreebiesbugUI设计资" },
    { id: "78", name: "云瑞", url: "https://www.yrucd.com", desc: "云瑞UI设计资源" },
    { id: "83", name: "UIkit.me", url: "http://www.uikit.me", desc: "UIkit.meUI设计资源" },
    { id: "77", name: "Freebie Supply", url: "https://freebiesupply.com", desc: "Freebie SupplyUI" },
    { id: "85", name: "PrincipleRepo", url: "http://principlerepo.com", desc: "PrincipleRepoUI设" },
    { id: "82", name: "uplabs", url: "https://www.uplabs.com", desc: "uplabsUI设计资源" },
    { id: "84", name: "Fribbble", url: "http://www.fribbble.com", desc: "FribbbleUI设计资源" },
    { id: "81", name: "ui8", url: "https://ui8.net", desc: "ui8UI设计资源" },
  ],
  "字体资源": [
    { id: "103", name: "FONTS2U", url: "https://fonts2u.com", desc: "FONTS2U免费字体下载" },
    { id: "96", name: "Typekit", url: "https://typekit.com", desc: "Typekit免费字体下载" },
    { id: "98", name: "字体传奇网", url: "http://ziticq.com", desc: "字体设计社区" },
    { id: "104", name: "Fontex", url: "http://www.fontex.org", desc: "Fontex免费字体下载" },
    { id: "101", name: "Urban Fonts", url: "https://www.urbanfonts.com", desc: "Urban Fonts免费字体下" },
    { id: "56", name: "ion icons", url: "http://ionicons.com", desc: "ion icons免费字体下载" },
    { id: "97", name: "方正字库", url: "http://www.foundertype.com", desc: "方正正版字库" },
    { id: "99", name: "私藏字体", url: "http://sicangziti.com", desc: "私藏字体免费字体下载" },
    { id: "95", name: "Google Font", url: "https://fonts.google.com", desc: "谷歌开源字体库" },
    { id: "107", name: "Da Font", url: "https://www.dafont.com", desc: "海量免费字体" },
    { id: "109", name: "Abstract Fonts", url: "http://www.abstractfonts.com", desc: "Abstract Fonts免费" },
    { id: "102", name: "Lost Type", url: "http://www.losttype.com", desc: "Lost Type免费字体下载" },
    { id: "100", name: "Fontsquirrel", url: "https://www.fontsquirrel.com", desc: "免费商用字体站" },
    { id: "106", name: "My Fonts", url: "http://www.myfonts.com", desc: "商业字体商店" },
    { id: "105", name: "FontM", url: "http://fontm.com", desc: "FontM免费字体下载" },
    { id: "108", name: "OnlineWebFonts", url: "https://www.onlinewebfonts.com", desc: "OnlineWebFonts免费" },
    { id: "new_字体资源_16", name: "猫啃网", url: "https://www.maoken.com", desc: "免费商用字体聚合" },
    { id: "new_字体资源_17", name: "字由", url: "https://www.hellofont.cn", desc: "字体管理激活工具" },
    { id: "new_字体资源_18", name: "阿里巴巴普惠体", url: "https://www.alibabafonts.com", desc: "阿里免费商用字体" },
    { id: "new_字体资源_19", name: "得意黑", url: "https://github.com/atelier-anchor/smiley-sans", desc: "开源斜体标题字体" },
    { id: "new_字体资源_20", name: "霞鹜文楷", url: "https://github.com/lxgw/LxgwWenKai", desc: "开源古籍楷体" },
  ],
  "摄影图库": [
    { id: "135", name: "lifeofpix", url: "http://www.lifeofpix.com", desc: "免费生活摄影素材" },
    { id: "133", name: "gratisography", url: "https://gratisography.com", desc: "创意怪诞免费图库" },
    { id: "131", name: "freenaturestock", url: "http://freenaturestock.com", desc: "freenaturestock免" },
    { id: "120", name: "librestock", url: "https://librestock.com", desc: "librestock免费高清图库" },
    { id: "142", name: "publicdomainarchive", url: "http://publicdomainarchive.com", desc: "publicdomainarch" },
    { id: "139", name: "magdeleine", url: "https://magdeleine.co/browse", desc: "magdeleine免费高清图库" },
    { id: "130", name: "thestocks", url: "http://thestocks.im", desc: "thestocks免费高清图库" },
    { id: "347", name: "图图ACG", url: "https://tupian.gq", desc: "图图ACG免费高清图库" },
    { id: "134", name: "imcreator", url: "http://imcreator.com/free", desc: "imcreator免费高清图库" },
    { id: "119", name: "visualhunt", url: "https://visualhunt.com", desc: "免费图库搜索引擎" },
    { id: "122", name: "SplitShire", url: "https://www.splitshire.com", desc: "免费高清摄影图库" },
    { id: "121", name: "pixabay", url: "https://pixabay.com", desc: "免费商用图片视频" },
    { id: "123", name: "StockSnap", url: "https://stocksnap.io", desc: "每周更新的免费图库" },
    { id: "128", name: "stokpic", url: "http://stokpic.com", desc: "stokpic免费高清图库" },
    { id: "136", name: "skitterphoto", url: "https://skitterphoto.com", desc: "免费高清摄影图库" },
    { id: "138", name: "skitterphoto", url: "https://skitterphoto.com", desc: "免费高清摄影图库" },
    { id: "125", name: "myphotopack", url: "https://myphotopack.com", desc: "myphotopack免费高清图" },
    { id: "140", name: "jeshoots", url: "http://jeshoots.com", desc: "jeshoots免费高清图库" },
    { id: "118", name: "Unsplash", url: "https://unsplash.com", desc: "免费高清摄影图库" },
    { id: "126", name: "Notaselfie", url: "http://notaselfie.com", desc: "Notaselfie免费高清图库" },
    { id: "137", name: "mmtstock", url: "https://mmtstock.com", desc: "mmtstock免费高清图库" },
    { id: "127", name: "papers", url: "http://papers.co", desc: "极简壁纸素材站" },
    { id: "141", name: "hdwallpapers", url: "https://www.hdwallpapers.net", desc: "高清壁纸下载站" },
    { id: "124", name: "albumarium", url: "http://albumarium.com", desc: "albumarium免费高清图库" },
    { id: "129", name: "55mm", url: "https://55mm.co/visuals", desc: "精选视觉图库" },
    { id: "132", name: "negativespace", url: "https://negativespace.co", desc: "免费摄影素材站" },
    { id: "new_摄影图库_26", name: "Pexels", url: "https://www.pexels.com", desc: "免费高清摄影图库CC0" },
    { id: "new_摄影图库_27", name: "ISO Republic", url: "https://isorepublic.com", desc: "免费高清图库可商用" },
    { id: "new_摄影图库_28", name: "Life of Pix", url: "https://www.lifeofpix.com", desc: "免费生活摄影素材" },
    { id: "new_摄影图库_29", name: "Foodiesfeed", url: "https://www.foodiesfeed.com", desc: "免费美食摄影图库" },
    { id: "new_摄影图库_30", name: "Magdeleine", url: "https://magdeleine.co", desc: "精选免费高清图库" },
  ],
  "其他网盘": [
    { id: "952", name: "梓澪の妙妙屋", url: "https://zi0.cc", desc: "梓澪の妙妙屋第三方资源网盘" },
    { id: "958", name: "洋芋资源站", url: "https://pan.51yangyu.cn", desc: "洋芋资源站第三方资源网盘" },
    { id: "955", name: "萤火虫资源站", url: "https://www.yhcres.top", desc: "萤火虫资源站第三方资源网盘" },
    { id: "962", name: "小乐的网盘", url: "https://share.xiaole88.com", desc: "小乐的网盘第三方资源网盘" },
    { id: "950", name: "七十二时.的资源站", url: "https://alist.qsesvick.top", desc: "七十二时.的资源站第三方资源网盘" },
    { id: "949", name: "七米蓝的仓库", url: "https://al.chirmyram.com", desc: "七米蓝的仓库第三方资源网盘" },
    { id: "951", name: "亿苯正经的OpenList库", url: "https://pan.lm379.cn", desc: "亿苯正经的OpenList库第三" },
    { id: "960", name: "布满灰尘的仓库", url: "https://pan.baiblog.ren", desc: "布满灰尘的仓库第三方资源网盘" },
    { id: "954", name: "AI Hobbyist 资源库", url: "https://res.acgnai.top", desc: "AI Hobbyist 资源库第" },
    { id: "1118", name: "雨云资源镜像站", url: "https://mirrors.rainyun.com", desc: "雨云资源镜像站第三方资源网盘" },
    { id: "957", name: "MOAPYR 资源站", url: "https://www.moapyr.com", desc: "MOAPYR 资源站第三方资源网" },
    { id: "956", name: "小爱音箱资源站", url: "https://xiaoai.qgmzmy.me", desc: "小爱音箱资源站第三方资源网盘" },
    { id: "959", name: "GistWillian的资源网盘", url: "https://share.gistwillan.top", desc: "GistWillian的资源网盘" },
    { id: "953", name: "Azad", url: "https://alist.azad.asia", desc: "Azad第三方资源网盘" },
    { id: "961", name: "Pengcheng", url: "https://pan.pengcheng.team", desc: "Pengcheng第三方资源网盘" },
  ],
  "AI工具": [
    { id: "1099", name: "chatgpt", url: "https://chatgpt.com", desc: "OpenAI智能对话助手" },
    { id: "1093", name: "1Chat.vin", url: "https://chat03.a1r.cc/#/chat/1002", desc: "1Chat.vinAI智能工具" },
    { id: "1096", name: "通义", url: "https://tongyi.aliyun.com/qianwen", desc: "阿里云AI大模型助手" },
    { id: "1084", name: "文心一言", url: "https://yiyan.baidu.com/agreement", desc: "百度AI大模型对话" },
    { id: "1085", name: "豆包", url: "https://www.doubao.com/chat", desc: "字节跳动AI智能助手" },
    { id: "1102", name: "AI Code Reviews", url: "https://bito.ai", desc: "AI Code ReviewsA" },
    { id: "1083", name: "DeepSeek", url: "https://chat.deepseek.com", desc: "深度求索AI大模型" },
    { id: "1086", name: "腾讯混元", url: "https://hunyuan.tencent.com", desc: "腾讯自研大模型" },
    { id: "1097", name: "讯飞星火", url: "https://xinghuo.xfyun.cn/desk?ch=xhweb_sax", desc: "科大讯飞AI助手" },
    { id: "1094", name: "欢迎来到AI的世界", url: "https://vip8.1ai.ink/chat?t12/?t12", desc: "欢迎来到AI的世界AI智能工具" },
    { id: "1095", name: "Kimi", url: "https://kimi.moonshot.cn", desc: "长文本AI对话助手" },
    { id: "1100", name: "秘塔写作猫", url: "https://xiezuocat.com", desc: "AI中文写作助手" },
    { id: "1090", name: "智谱清言", url: "https://chatglm.cn/main/guest?lang=zh", desc: "智谱AI大模型助手" },
    { id: "1101", name: "智谱AI开放平台", url: "https://www.bigmodel.cn/login", desc: "智谱AI开放平台AI智能工具" },
    { id: "1092", name: "AI问答宝", url: "https://ai.wendabao-d.net/#/chat/1738810429887", desc: "AI问答宝AI智能工具" },
    { id: "1089", name: "360 AI", url: "https://ai.360.cn", desc: "360旗下AI助手" },
    { id: "1091", name: "AI办公智能体先行者", url: "https://www.tiangong.cn", desc: "AI办公智能体先行者AI智能工具" },
    { id: "1088", name: "鱼聪明AI", url: "https://www.yucongming.com/?current=1", desc: "鱼聪明AIAI智能工具" },
    { id: "1103", name: "Kodezi", url: "https://kodezi.com", desc: "KodeziAI智能工具" },
    { id: "1087", name: "百小应", url: "https://ying.baichuan-ai.com/chat", desc: "百川智能AI助手" },
    { id: "new_AI工具_20", name: "Coze扣子", url: "https://www.coze.cn", desc: "字节AI智能体开发平台" },
    { id: "new_AI工具_21", name: "商汤商量", url: "https://chat.sensetime.com", desc: "商汤大模型对话助手" },
    { id: "new_AI工具_22", name: "HolaAI", url: "https://holaai.top", desc: "AI工具导航聚合站" },
    { id: "new_AI工具_23", name: "腾讯元宝", url: "https://yuanbao.tencent.com", desc: "腾讯AI助手，腾讯混元" },
    { id: "new_AI工具_24", name: "Grok", url: "https://grok.com", desc: "xAI智能对话助手" },
    { id: "new_AI工具_25", name: "Claude", url: "https://claude.ai", desc: "Anthropic大模型助手" },
  ],
  "网盘云储": [
    { id: "863", name: "百度网盘", url: "https://pan.baidu.com", desc: "国民级云存储网盘" },
    { id: "870", name: "阿里云盘", url: "https://www.aliyundrive.com", desc: "阿里云免费网盘" },
    { id: "871", name: "115网盘", url: "https://115.com", desc: "老牌云存储网盘" },
    { id: "868", name: "Google云盘", url: "https://www.google.com/drive", desc: "谷歌云存储服务" },
    { id: "869", name: "天翼云盘", url: "https://cloud.189.cn/web/login.html", desc: "中国电信云盘" },
    { id: "864", name: "盘它云网盘", url: "https://pantayun.com/invite/?code=S6OgV3", desc: "盘它云网盘云存储网盘服务" },
    { id: "865", name: "边乐云网盘", url: "https://yun.bianyue.cn", desc: "边乐云网盘云存储网盘服务" },
    { id: "866", name: "OneDrive", url: "https://onedrive.live.com", desc: "微软云存储服务" },
    { id: "867", name: "微云", url: "https://www.weiyun.com", desc: "腾讯云存储网盘" },
    { id: "new_网盘云储_9", name: "夸克网盘", url: "https://pan.quark.cn", desc: "阿里系网盘，传输快" },
    { id: "new_网盘云储_10", name: "123云盘", url: "https://www.123pan.com", desc: "免费云存储分享" },
    { id: "new_网盘云储_11", name: "蓝奏云", url: "https://www.lanzou.com", desc: "免登录分享小文件" },
    { id: "new_网盘云储_12", name: "坚果云", url: "https://www.jianguoyun.com", desc: "同步盘，团队协作" },
    { id: "new_网盘云储_13", name: "奶牛快传", url: "https://cowtransfer.com", desc: "免登录大文件传输" },
  ],
  "购物网站": [
    { id: "1080", name: "免费领流量卡", url: "https://h5.lot-ml.com/ProductEn/Index/03607e34ea182d64", desc: "免费领流量卡苹果周边购物" },
    { id: "1105", name: "苹果证书", url: "https://puaaa.cn/shop/10.html", desc: "苹果证书苹果周边购物" },
    { id: "1140", name: "聚浪科技", url: "http://www.jlqc.top", desc: "聚浪科技苹果周边购物" },
  ],
  "社区资讯": [
    { id: "18", name: "数英网", url: "https://www.digitaling.com", desc: "数字营销案例平台" },
    { id: "738", name: "WordPress大学", url: "https://www.wpdaxue.com", desc: "WordPress教程" },
    { id: "21", name: "优阁网", url: "http://www.uigreat.com", desc: "优阁网科技社区与资讯" },
    { id: "16", name: "雷锋网", url: "https://www.leiphone.com", desc: "科技资讯媒体" },
    { id: "19", name: "猎云网", url: "http://www.lieyunwang.com", desc: "创业创投资讯" },
    { id: "248", name: "站长资讯平台", url: "http://www.1994july.club", desc: "站长资讯平台科技社区与资讯" },
    { id: "20", name: "产品壹佰", url: "http://www.chanpin100.com", desc: "产品经理学习社区" },
    { id: "17", name: "36kr", url: "http://36kr.com", desc: "科技商业媒体" },
    { id: "new_社区资讯_8", name: "站酷", url: "https://www.zcool.com.cn", desc: "设计师创意社区" },
    { id: "new_社区资讯_9", name: "花瓣网", url: "https://huaban.com", desc: "设计灵感采集平台" },
    { id: "new_社区资讯_10", name: "Behance", url: "https://www.behance.net", desc: "全球设计师作品集" },
    { id: "new_社区资讯_11", name: "Dribbble", url: "https://dribbble.com", desc: "全球设计灵感社区" },
    { id: "new_社区资讯_12", name: "Pinterest", url: "https://www.pinterest.com", desc: "全球灵感图库" },
    { id: "new_社区资讯_13", name: "古田路9号", url: "https://www.gtn9.com", desc: "品牌设计分享平台" },
    { id: "new_社区资讯_14", name: "UI中国", url: "https://www.ui.cn", desc: "UI设计垂直社区" },
    { id: "new_社区资讯_15", name: "优设网", url: "https://www.uisdc.com", desc: "设计教程与资源" },
  ],
  "UED团队": [
    { id: "200", name: "腾讯CDC", url: "http://cdc.tencent.com", desc: "腾讯CDCUED团队博客" },
    { id: "208", name: "京东设计中心", url: "http://jdc.jd.com", desc: "京东设计中心UED团队博客" },
    { id: "198", name: "eico design", url: "http://eicodesign.com", desc: "eico designUED团队" },
    { id: "201", name: "TGideas", url: "http://tgideas.qq.com", desc: "TGideasUED团队博客" },
    { id: "202", name: "ISUX", url: "https://isux.tencent.com", desc: "ISUXUED团队博客" },
    { id: "197", name: "Google Design", url: "https://design.google", desc: "Google DesignUED" },
    { id: "205", name: "U一点", url: "http://www.aliued.cn", desc: "U一点UED团队博客" },
    { id: "209", name: "百度企业产品用户体验中心", url: "http://eux.baidu.com", desc: "百度企业产品用户体验中心UED团" },
    { id: "196", name: "Facebook Design", url: "http://facebook.design", desc: "Facebook DesignU" },
    { id: "388", name: "WordPress主题君", url: "https://www.ztjun.com", desc: "WordPress主题君UED团" },
    { id: "210", name: "携程设计委员会", url: "http://ued.ctrip.com", desc: "携程设计委员会UED团队博客" },
    { id: "199", name: "nice design", url: "http://www.niceui.cn", desc: "nice designUED团队" },
    { id: "207", name: "百度用户体验中心", url: "http://ued.baidu.com", desc: "百度用户体验中心UED团队博客" },
    { id: "195", name: "Airbnb Design", url: "https://airbnb.design", desc: "Airbnb DesignUED" },
  ],
};