// 甜甜导航 - 站点数据（自动生成）
export interface Site {
  id: string;
  name: string;
  url: string;
  desc: string;
  icon?: string;
}

export const categories_part2: Record<string, Site[]> = {
  "图形创意": [
    { id: "150", name: "Affinity Designer", url: "https://affinity.serif.com", desc: "Affinity Designe" },
    { id: "149", name: "photoshop", url: "https://www.adobe.com/cn/products/photoshop.html", desc: "photoshop图形创意工具" },
    { id: "155", name: "Blender", url: "https://www.blender.org", desc: "Blender图形创意工具" },
    { id: "151", name: "Illustrator", url: "https://www.adobe.com/cn/products/illustrator", desc: "Illustrator图形创意工" },
    { id: "152", name: "indesign", url: "http://www.adobe.com/cn/products/indesign.html", desc: "indesign图形创意工具" },
    { id: "154", name: "3ds-max", url: "https://www.autodesk.com/products/3ds-max/overview", desc: "3ds-max图形创意工具" },
    { id: "153", name: "cinema-4d", url: "https://www.maxon.net/en/products/cinema-4d/overview", desc: "cinema-4d图形创意工具" },
    { id: "new_图形创意_7", name: "This Person Does Not Exist", url: "https://thispersondoesnotexist.com", desc: "AI生成人像" },
  ],
  "在线工具": [
    { id: "188", name: "稿定抠图", url: "https://www.gaoding.com", desc: "在线智能抠图" },
    { id: "183", name: "goqr", url: "http://goqr.me", desc: "goqr在线实用工具" },
    { id: "184", name: "ezgif", url: "https://ezgif.com", desc: "GIF在线编辑" },
    { id: "186", name: "screen sizes", url: "http://screensiz.es", desc: "screen sizes在线实用" },
    { id: "185", name: "Android 9 patch", url: "http://inloop.github.io/shadow4android", desc: "Android 9 patch在" },
    { id: "187", name: "svgomg", url: "https://jakearchibald.github.io/svgomg", desc: "SVG在线优化" },
    { id: "182", name: "tinypng", url: "https://tinypng.com", desc: "智能压缩PNG/JPG" },
    { id: "new_在线工具_7", name: "iLovePDF", url: "https://www.ilovepdf.com/zh-cn", desc: "在线PDF处理全家桶" },
    { id: "new_在线工具_8", name: "PDF24 Tools", url: "https://tools.pdf24.org", desc: "免费PDF工具箱" },
    { id: "new_在线工具_9", name: "改图鸭", url: "https://www.gaituya.com", desc: "在线图片处理工具" },
    { id: "new_在线工具_10", name: "ConvertFree", url: "https://convertfree.io", desc: "浏览器端格式转换" },
    { id: "new_在线工具_11", name: "i2IMG", url: "https://www.i2img.com", desc: "AI图片增强工具箱" },
    { id: "new_在线工具_12", name: "Office-Converter", url: "https://www.office-converter.com", desc: "万能格式转换" },
    { id: "new_在线工具_13", name: "Let Compress", url: "https://letcompress.com", desc: "浏览器端文件压缩" },
  ],
  "界面设计": [
    { id: "161", name: "figma", url: "https://www.figma.com", desc: "在线UI协作设计" },
    { id: "160", name: "Muse CC", url: "https://creative.adobe.com/zh-cn/products/download/muse", desc: "Muse CC界面设计工具" },
    { id: "158", name: "invisionapp", url: "https://www.invisionapp.com", desc: "在线交互原型设计" },
    { id: "157", name: "Adobe XD", url: "http://www.adobe.com/products/xd.html", desc: "Adobe界面设计工具" },
    { id: "159", name: "marvelapp", url: "https://marvelapp.com", desc: "在线原型设计工具" },
    { id: "new_界面设计_5", name: "Sketch", url: "https://www.sketch.com", desc: "Mac端UI设计工具" },
    { id: "new_界面设计_6", name: "Framer", url: "https://www.framer.com", desc: "交互原型设计" },
    { id: "new_界面设计_7", name: "ProtoPie", url: "https://www.protopie.io", desc: "高保真交互原型" },
  ],
  "平面素材": [
    { id: "241", name: "图虫图库", url: "https://stock.tuchong.com", desc: "图虫图库平面设计素材" },
    { id: "73", name: "素材搜索", url: "http://so.ui001.com", desc: "素材搜索平面设计素材" },
    { id: "64", name: "wallhalla", url: "https://wallhalla.com", desc: "wallhalla平面设计素材" },
    { id: "68", name: "千库网", url: "http://588ku.com", desc: "千库网平面设计素材" },
    { id: "74", name: "PS饭团网", url: "http://psefan.com", desc: "PS饭团网平面设计素材" },
    { id: "75", name: "素材中国", url: "http://www.sccnn.com", desc: "素材中国平面设计素材" },
    { id: "70", name: "90设计", url: "http://90sheji.com", desc: "90设计平面设计素材" },
    { id: "71", name: "昵图网", url: "http://www.nipic.com", desc: "昵图网平面设计素材" },
    { id: "67", name: "千图网", url: "http://www.58pic.com", desc: "千图网平面设计素材" },
    { id: "72", name: "懒人图库", url: "http://www.lanrentuku.com", desc: "懒人图库平面设计素材" },
    { id: "707", name: "快图网", url: "http://www.kuaipng.com", desc: "快图网平面设计素材" },
    { id: "69", name: "我图网", url: "http://www.ooopic.com", desc: "我图网平面设计素材" },
    { id: "66", name: "Medialoot", url: "https://medialoot.com", desc: "Medialoot平面设计素材" },
    { id: "63", name: "freepik", url: "https://www.freepik.com", desc: "freepik平面设计素材" },
    { id: "65", name: "365PSD", url: "https://365psd.com", desc: "365PSD平面设计素材" },
  ],
  "LOGO设计": [
    { id: "61", name: "World Vector Logo", url: "https://worldvectorlogo.com", desc: "World Vector Log" },
    { id: "62", name: "Instant Logo Search", url: "http://instantlogosearch.com", desc: "Instant Logo Sea" },
    { id: "60", name: "iOS Icon Gallery", url: "http://iosicongallery.com", desc: "iOS Icon Gallery" },
    { id: "58", name: "Iconsfeed", url: "http://www.iconsfeed.com", desc: "IconsfeedLOGO设计工" },
  ],
  "Mockup": [
    { id: "113", name: "Threed", url: "http://threed.io", desc: "ThreedMockup样机素材" },
    { id: "111", name: "Dunnnk", url: "http://dunnnk.com", desc: "DunnnkMockup样机素材" },
    { id: "110", name: "MockupZone", url: "https://mockup.zone", desc: "MockupZoneMockup" },
    { id: "114", name: "Mockup World", url: "https://free.lstore.graphics", desc: "Mockup WorldMock" },
    { id: "112", name: "Graphberry", url: "http://www.graphberry.com", desc: "GraphberryMockup" },
    { id: "117", name: "For Graphic TM", url: "http://forgraphictm.com", desc: "For Graphic TMMo" },
    { id: "116", name: "pixeden", url: "https://www.pixeden.com", desc: "pixedenMockup样机素" },
    { id: "115", name: "Lstore", url: "https://free.lstore.graphics", desc: "LstoreMockup样机素材" },
  ],
  "PPT资源": [
    { id: "143", name: "OfficePLUS", url: "http://www.officeplus.cn/Template/Home.shtml", desc: "OfficePLUSPPT模板资" },
    { id: "148", name: "5百丁", url: "http://ppt.500d.me", desc: "5百丁PPT模板资源" },
    { id: "144", name: "优品PPT", url: "http://www.ypppt.com", desc: "优品PPTPPT模板资源" },
    { id: "145", name: "PPT+", url: "http://www.pptplus.cn", desc: "PPT+PPT模板资源" },
    { id: "146", name: "PPTMind", url: "http://www.pptmind.com", desc: "PPTMindPPT模板资源" },
    { id: "147", name: "tretars", url: "http://www.tretars.com/ppt-templates", desc: "tretarsPPT模板资源" },
  ],
  "Sketch资源": [
    { id: "91", name: "Sketch中文网", url: "http://www.sketchcn.com", desc: "Sketch中文网Sketch插" },
    { id: "87", name: "Sketch Measure", url: "http://utom.design/measure", desc: "Sketch MeasureSk" },
    { id: "88", name: "Sketch App Sources", url: "https://www.sketchappsources.com", desc: "Sketch App Sourc" },
    { id: "90", name: "Sketch Hunt", url: "http://sketchhunt.com", desc: "Sketch HuntSketc" },
    { id: "94", name: "Sketchcasts", url: "https://www.sketchcasts.net", desc: "SketchcastsSketc" },
    { id: "86", name: "Sketch", url: "https://sketchapp.com", desc: "Mac端UI设计工具" },
    { id: "93", name: "Awesome Sketch Plugins", url: "https://awesome-sket.ch", desc: "Awesome Sketch P" },
  ],
  "图标素材": [
    { id: "55", name: "Font Awesome Icon", url: "https://fontawesome.com/icons", desc: "经典字体图标库" },
    { id: "57", name: "Simpleline Icons", url: "http://simplelineicons.com", desc: "简洁线性图标" },
    { id: "53", name: "UICloud", url: "http://ui-cloud.com", desc: "UI设计素材云" },
    { id: "54", name: "Material icons", url: "https://material.io/icons", desc: "谷歌官方图标库" },
    { id: "48", name: "Icon Archive", url: "http://www.iconarchive.com", desc: "历史图标存档库" },
    { id: "51", name: "easyicon", url: "http://www.easyicon.net", desc: "免费图标下载" },
    { id: "50", name: "IcoMoonApp", url: "https://icomoon.io/app", desc: "图标字体生成器" },
    { id: "46", name: "iconfont", url: "http://www.iconfont.cn", desc: "阿里矢量图标库" },
    { id: "52", name: "flaticon", url: "https://www.flaticon.com", desc: "全球海量图标库" },
    { id: "45", name: "Iconfinder", url: "https://www.iconfinder.com", desc: "付费高清图标库" },
    { id: "47", name: "iconmonstr", url: "https://iconmonstr.com", desc: "简洁开源图标库" },
    { id: "49", name: "FindIcons", url: "https://findicons.com", desc: "图标聚合搜索" },
    { id: "new_图标素材_12", name: "Heroicons", url: "https://heroicons.com", desc: "开源线性图标库" },
    { id: "new_图标素材_13", name: "Tabler Icons", url: "https://tabler.io/icons", desc: "1200+开源图标" },
    { id: "new_图标素材_14", name: "Remix Icon", url: "https://remixicon.com", desc: "开源线性图标集" },
    { id: "new_图标素材_15", name: "Lucide", url: "https://lucide.dev", desc: "开源清晰图标库" },
    { id: "new_图标素材_16", name: "The Noun Project", url: "https://thenounproject.com", desc: "全球图标素材库" },
    { id: "new_图标素材_17", name: "Undraw", url: "https://undraw.co", desc: "免费可定制插画" },
    { id: "new_图标素材_18", name: "Openclipart", url: "https://openclipart.org", desc: "公有领域剪贴画库" },
  ],
};