// 甜甜导航 - 站点数据（自动生成）
export interface Site {
  id: string;
  name: string;
  url: string;
  desc: string;
  icon?: string;
}
export const categories_part3: Record<string, Site[]> = {
  "UI资源": [
    { id: "9", name: "UI中国", url: "http://www.ui.cn", desc: "图形交互与界面设计交流、作品展示、学习平台。" },
    { id: "240", name: "UI自用导航", url: "http://dh.simple.red", desc: "UI设计师自用导航" },
    { id: "79", name: "Designmodo", url: "https://designmodo.com", desc: "Web Design Blog and Shop" },
    { id: "80", name: "稀土区", url: "https://xituqu.com", desc: "优质设计开发资源分享" },
    { id: "76", name: "Freebiesbug", url: "https://freebiesbug.com", desc: "Hand-picked resources for web designer and developers, constantly updated." },
    { id: "78", name: "云瑞", url: "https://www.yrucd.com", desc: "优秀设计资源的分享网站" },
    { id: "83", name: "UIkit.me", url: "http://www.uikit.me", desc: "最便捷新鲜的uikit资源下载网站" },
    { id: "77", name: "Freebie Supply", url: "https://freebiesupply.com", desc: "Free Resources For Designers" },
    { id: "85", name: "PrincipleRepo", url: "http://principlerepo.com", desc: "Free, High Quality Principle Resources" },
    { id: "82", name: "uplabs", url: "https://www.uplabs.com", desc: "Daily resources for product designers & developers" },
    { id: "84", name: "Fribbble", url: "http://www.fribbble.com", desc: "Free PSD files and other free design resources by Dribbblers." },
    { id: "81", name: "ui8", url: "https://ui8.net", desc: "UI Kits, Wireframe Kits, Templates, Icons and More" },
  ],
  "字体资源": [
    { id: "103", name: "FONTS2U", url: "https://fonts2u.com", desc: "Download free fonts for Windows and Macintosh." },
    { id: "96", name: "Typekit", url: "https://typekit.com", desc: "Quality fonts from the world’s best foundries." },
    { id: "98", name: "字体传奇网", url: "http://ziticq.com", desc: "中国首个字体品牌设计师交流网" },
    { id: "104", name: "Fontex", url: "http://www.fontex.org", desc: "Free Fonts to Download + Premium Typefaces" },
    { id: "101", name: "Urban Fonts", url: "https://www.urbanfonts.com", desc: "Download Free Fonts and Free Dingbats." },
    { id: "97", name: "方正字库", url: "http://www.foundertype.com", desc: "方正字库官方网站" },
    { id: "56", name: "ion icons", url: "http://ionicons.com", desc: "The premium icon font for Ionic Framework" },
    { id: "99", name: "私藏字体", url: "http://sicangziti.com", desc: "优质字体免费下载站" },
    { id: "107", name: "Da Font", url: "https://www.dafont.com", desc: "Archive of freely downloadable fonts." },
    { id: "95", name: "Google Font", url: "https://fonts.google.com", desc: "Making the web more beautiful, fast, and open through great typography" },
    { id: "109", name: "Abstract Fonts", url: "http://www.abstractfonts.com", desc: "Abstract Fonts (13,866 free fonts)" },
    { id: "102", name: "Lost Type", url: "http://www.losttype.com", desc: "Lost Type is a Collaborative Digital Type Foundry" },
    { id: "100", name: "Fontsquirrel", url: "https://www.fontsquirrel.com", desc: "FREE fonts for graphic designers" },
    { id: "105", name: "FontM", url: "http://fontm.com", desc: "Free Fonts" },
    { id: "106", name: "My Fonts", url: "http://www.myfonts.com", desc: "Fonts for Print, Products & Screens" },
    { id: "108", name: "OnlineWebFonts", url: "https://www.onlinewebfonts.com", desc: "WEB Free Fonts for Windows and Mac / Font free Download" },
  ],
  "其他网盘": [
    { id: "952", name: "梓澪の妙妙屋", url: "https://zi0.cc", desc: "梓澪の妙妙屋 | 免费Galgame仓库&下载站" },
    { id: "958", name: "洋芋资源站", url: "https://pan.51yangyu.cn", desc: "洋芋资源站" },
    { id: "955", name: "萤火虫资源站", url: "https://www.yhcres.top", desc: "" },
    { id: "962", name: "小乐的网盘", url: "https://share.xiaole88.com", desc: "小乐的网盘" },
    { id: "950", name: "七十二时.的资源站", url: "https://alist.qsesvick.top", desc: "七十二时.的资源站" },
    { id: "949", name: "七米蓝的仓库", url: "https://al.chirmyram.com", desc: "OpenList" },
    { id: "951", name: "亿苯正经的OpenList库", url: "https://pan.lm379.cn", desc: "lm379" },
    { id: "960", name: "布满灰尘的仓库", url: "https://pan.baiblog.ren", desc: "布满灰尘的仓库" },
    { id: "954", name: "AI Hobbyist 资源库", url: "https://res.acgnai.top", desc: "AI Hobbyist 资源库" },
    { id: "1118", name: "雨云资源镜像站", url: "https://mirrors.rainyun.com", desc: "雨云资源镜像站" },
    { id: "957", name: "MOAPYR 资源站", url: "https://www.moapyr.com", desc: "MOAPYR 资源站" },
    { id: "956", name: "小爱音箱资源站", url: "https://xiaoai.qgmzmy.me", desc: "小爱音箱资源站" },
    { id: "959", name: "GistWillian的资源网盘", url: "https://share.gistwillan.top", desc: "GistWillian的资源网盘" },
    { id: "953", name: "Azad", url: "https://alist.azad.asia", desc: "Azad - 个人云盘" },
    { id: "961", name: "Pengcheng", url: "https://pan.pengcheng.team", desc: "Pengcheng's Download" },
  ],
  "AI工具": [
    { id: "1099", name: "chatgpt", url: "https://chatgpt.com", desc: "Attention Required! | Cloudflare" },
    { id: "1093", name: "1Chat.vin", url: "https://chat03.a1r.cc/#/chat/1002", desc: "1Chat.vin国内免费且最快的智能AI" },
    { id: "1096", name: "通义", url: "https://tongyi.aliyun.com/qianwen", desc: "" },
    { id: "1084", name: "文心一言", url: "https://yiyan.baidu.com/agreement", desc: "" },
    { id: "1085", name: "豆包", url: "https://www.doubao.com/chat", desc: "" },
    { id: "1102", name: "AI Code Reviews", url: "https://bito.ai", desc: "AI Code Reviews designed for modern dev teams. Cut review time, improve code quality, and ship with confidence — with contextual, senior-level feedback." },
    { id: "1083", name: "DeepSeek", url: "https://chat.deepseek.com", desc: "Chat with DeepSeek AI – your intelligent assistant for coding, content creation, file reading, and more. Upload documents, engage in long-context conversations, and get expert help in AI, natural language processing, and beyond. | 深度求索（DeepSeek）助力编程代码开发、创意写作、文件处理等任务，支持文件上传及长文本对话，随时为您提供高效的AI支持。" },
    { id: "1086", name: "腾讯混元", url: "https://hunyuan.tencent.com", desc: "" },
    { id: "1097", name: "讯飞星火", url: "https://xinghuo.xfyun.cn/desk?ch=xhweb_sax", desc: "讯飞星火大模型，是由科大讯飞推出的新一代认知智能大模型，拥有跨领域的知识和语言理解能力，能够基于自然对话方式理解与执行任务，提供语言理解、知识问答、逻辑推理、数学题解答、代码理解与编写等多种能力。" },
    { id: "1094", name: "欢迎来到AI的世界", url: "https://vip8.1ai.ink/chat?t12/?t12", desc: "欢迎来到AI的世界" },
    { id: "1095", name: "Kimi", url: "https://kimi.moonshot.cn", desc: "Kimi K2 是我们最新升级的 AI 助手，擅长推理、编程和调用工具，帮助你高效解决复杂问题。无论是工作、学习还是创作，都可以试试用 Kimi K2 来完成。" },
    { id: "1100", name: "秘塔写作猫", url: "https://xiezuocat.com", desc: "秘塔写作猫" },
    { id: "1090", name: "智谱清言", url: "https://chatglm.cn/main/guest?lang=zh", desc: "" },
    { id: "1101", name: "智谱AI开放平台", url: "https://www.bigmodel.cn/login", desc: "智谱大模型开放平台-新一代国产自主通用AI大模型开放平台，是国内大模型排名前列的大模型网站，研发了多款LLM模型，多模态视觉模型产品，致力于将AI产品技术与行业场景双轮驱动的中国先进的认知智能技术和千行百业应用相结合，构建更高精度、高效率、通用化的AI开发新模式和企业级解决方案，实现智谱大模型的产业化，将AI的好处带给每个人。" },
    { id: "1092", name: "AI问答宝", url: "https://ai.wendabao-d.net/#/chat/1738810429887", desc: "免费人工智能在线对话问答，免费在线AI论文写作、绘图，免费ChatGPT Plus" },
    { id: "1089", name: "360 AI", url: "https://ai.360.cn", desc: "360安全云" },
    { id: "1091", name: "AI办公智能体先行者", url: "https://www.tiangong.cn", desc: "天工Skywork是一款具备超强DeepResearch能力的全新AI Office智能体，通过3个专家agent和1个通用agent，让AI深度研究，一键生成AI文档、AI PPT、AI表格，高效应对各类办公、学习场景；也支持网页html、图像、视频、有声书、绘本等多种形式的创意内容创作，激发无限灵感。 天工Skywork融合先进的多模态理解与深度检索分析技术，一问即得科研级、专业级、咨询级的高质量结果，帮助你摆脱繁琐事务，显著提升效率。 无论你是职场白领、科研人员、大学生、研究生，还是自媒体KOL，天工Skywork都将是你值得信赖的智能伙伴，助你专注思考、释放创造力。" },
    { id: "1088", name: "鱼聪明AI", url: "https://www.yucongming.com/?current=1", desc: "" },
    { id: "1103", name: "Kodezi", url: "https://kodezi.com", desc: "Kodezi is your AI CTO—an autonomous operating system that maintains, evolves, and governs modern codebases. Seamlessly integrated across your stack, it ensures your software remains healthy, scalable, and always ready to ship." },
    { id: "1087", name: "百小应", url: "https://ying.baichuan-ai.com/chat", desc: "查指南、找文献、搜药品，每一条医学建议都有据可依！" },
  ],
  "网盘云储": [
    { id: "863", name: "百度网盘", url: "https://pan.baidu.com", desc: "百度网盘是一款国民级产品" },
    { id: "870", name: "阿里云盘", url: "https://www.aliyundrive.com", desc: "阿里云盘是一款速度快的个人网盘" },
    { id: "871", name: "115网盘", url: "https://115.com", desc: "115，一生相伴" },
    { id: "868", name: "Google云盘", url: "https://www.google.com/drive", desc: "轻松安全地访问您的所有内容" },
    { id: "869", name: "天翼云盘", url: "https://cloud.189.cn/web/login.html", desc: "珍藏美好生活 家庭云" },
    { id: "864", name: "盘它云网盘", url: "https://pantayun.com/invite/?code=S6OgV3", desc: "盘它云网盘是向广大用户提供上传空间和技术的信息存储空间服务平台。" },
    { id: "865", name: "边乐云网盘", url: "https://yun.bianyue.cn", desc: "边乐云网盘致力于为用户提供安全稳定的云存储产品" },
    { id: "866", name: "OneDrive", url: "https://onedrive.live.com", desc: "Store photos and docs online. Access them from any PC, Mac or phone. Create and work together on Word, Excel or PowerPoint documents." },
    { id: "867", name: "微云", url: "https://www.weiyun.com", desc: "微云是腾讯公司为用户精心打造的一项智能云服务" },
  ],
  "购物网站": [
    { id: "1080", name: "免费领流量卡", url: "https://h5.lot-ml.com/ProductEn/Index/03607e34ea182d64", desc: "" },
    { id: "1105", name: "苹果证书", url: "https://puaaa.cn/shop/10.html", desc: "稳定的苹果证书！", icon: "https://puaaa.cn/wp-content/uploads/2026/05/bluesky.svg" },
    { id: "1140", name: "聚浪科技", url: "http://www.jlqc.top", desc: "" },
  ],
  "社区资讯": [
    { id: "18", name: "数英网", url: "https://www.digitaling.com", desc: "数字媒体及职业招聘网站" },
    { id: "738", name: "WordPress大学", url: "https://www.wpdaxue.com", desc: "WordPress大学专注于wordpress建站教学,提供wordpress主题,wordpres" },
    { id: "21", name: "优阁网", url: "http://www.uigreat.com", desc: "UI设计师学习交流社区" },
    { id: "16", name: "雷锋网", url: "https://www.leiphone.com", desc: "人工智能和智能硬件领域的互联网科技媒体" },
    { id: "19", name: "猎云网", url: "http://www.lieyunwang.com", desc: "互联网创业项目推荐和创业创新资讯" },
    { id: "248", name: "站长资讯平台", url: "http://www.1994july.club", desc: "站长资讯平台为个人站长与企业网络提供全面的站长资讯，一站式网络解决方案，我们一直致力为中文网站提供动" },
    { id: "20", name: "产品壹佰", url: "http://www.chanpin100.com", desc: "为产品经理爱好者提供最优质的产品资讯、原创内容和相关视频课程" },
    { id: "17", name: "36kr", url: "http://36kr.com", desc: "创业资讯、科技新闻" },
  ],
  "UED团队": [
    { id: "200", name: "腾讯CDC", url: "http://cdc.tencent.com", desc: "腾讯CDC关注于互联网视觉设计、交互设计、用户研究、前端开发。" },
    { id: "208", name: "京东设计中心", url: "http://jdc.jd.com", desc: "京东设计中心" },
    { id: "198", name: "eico design", url: "http://eicodesign.com", desc: "数字化咨询与产品专家" },
    { id: "201", name: "TGideas", url: "http://tgideas.qq.com", desc: "TGideas隶属于腾讯公司互动娱乐业务系统的专业推广类设计团队" },
    { id: "202", name: "ISUX", url: "https://isux.tencent.com", desc: "腾讯社交用户体验设计部" },
    { id: "197", name: "Google Design", url: "https://design.google", desc: "Google Design" },
    { id: "205", name: "U一点", url: "http://www.aliued.cn", desc: "阿里巴巴（中国站）用户体验设计部博客U一点设计 UED团队" },
    { id: "209", name: "百度企业产品用户体验中心", url: "http://eux.baidu.com", desc: "百度企业产品用户体验中心" },
    { id: "196", name: "Facebook Design", url: "http://facebook.design", desc: "Facebook Design" },
    { id: "388", name: "WordPress主题君", url: "https://www.ztjun.com", desc: "精选免费WordPress主题模板下载", icon: "https://nav.iowen.cn/wp-content/uploads/2020/03/20200305153742_fc6e5c59.png" },
    { id: "210", name: "携程设计委员会", url: "http://ued.ctrip.com", desc: "携程设计委员会-Ctrip Design Committee" },
    { id: "199", name: "nice design", url: "http://www.niceui.cn", desc: "nicedesign奈思设计是领先的用户体验设计与互联网品牌建设公司" },
    { id: "207", name: "百度用户体验中心", url: "http://ued.baidu.com", desc: "百度用户体验中心" },
    { id: "195", name: "Airbnb Design", url: "https://airbnb.design", desc: "Airbnb Design" },
  ],
};
