// 甜甜导航 - 站点数据（自动生成）
export interface Site {
  id: string;
  name: string;
  url: string;
  desc: string;
  icon?: string;
}
export const categories_part1: Record<string, Site[]> = {
  "iOS网盘": [
    { id: "887", name: "甜甜网盘", url: "https://pan.puaaa.cn", desc: "免费免费一直免费开放！", icon: "https://iosdh.cn/wp-content/uploads/2025/10/%E7%94%9C%E7%94%9C%E7%BD%91%E7%9B%98icon.svg" },
    { id: "928", name: "宅哥技术网盘", url: "https://pan.312752.cn", desc: "宅哥技术网盘" },
    { id: "931", name: "IPA分享站", url: "https://pan.cjq6525.xyz", desc: "IPA分享站" },
    { id: "925", name: "91网盘", url: "https://alist.91ios.fun", desc: "91网盘-ipa资源网盘" },
    { id: "935", name: "DaPeng网盘", url: "https://wp.sha0p.cn", desc: "DaPeng网盘｜iOS资源分享网-IPA资源库-巨魔商店IPA软件资源-网络资源分享" },
    { id: "930", name: "IOS神器", url: "https://iossq.top", desc: "IOS神器" },
    { id: "923", name: "平凡", url: "https://pan.iosi.vip", desc: "平凡" },
    { id: "905", name: "小海网盘", url: "https://pan.weblyc.cn", desc: "小海资源分享网盘" },
    { id: "912", name: "鹏客网盘", url: "https://peck.cool", desc: "peckios" },
    { id: "932", name: "薛萌萌网盘", url: "https://pan.xmmqm.cn", desc: "薛萌萌网盘" },
    { id: "946", name: "爱锋助手资源盘", url: "https://pan.yhios.cn", desc: "爱锋助手资源盘专注于iOS应用分享，提供免费企业证书、IPA签名包、精品iOS软件与游戏、微信多开插件、IPA安装包、微信主题美化等，支持在线安装与极速下载。" },
    { id: "908", name: "顷酉网盘", url: "https://pan.586226.xyz", desc: "顷酉网盘-为果粉提供的资源站" },
    { id: "913", name: "优创网盘", url: "https://pan.ucgod.cn", desc: "优创网盘 - iuczy优创AppStore" },
    { id: "924", name: "小艾网盘", url: "http://dh.agxmt.com", desc: "小艾网盘" },
    { id: "927", name: "萌仙科技网盘", url: "https://pan.mxwlcm.cn", desc: "萌仙科技网盘" },
    { id: "926", name: "知网云盘", url: "https://pan.xyyh.xyz", desc: "知网云盘" },
    { id: "914", name: "酷乐网盘", url: "https://pan.6789o.com", desc: "酷乐网盘" },
    { id: "899", name: "DumpApp", url: "https://pan.dumpapp.com", desc: "DumpApp" },
    { id: "910", name: "微速云盘", url: "https://pan.iosdz.cn", desc: "微速 云盘" },
    { id: "901", name: "小萝卜云盘", url: "https://yun.lbbb.cc", desc: "小萝卜云盘" },
  ],
  "TG资源": [
    { id: "1070", name: "资源分享客栈-Applnn", url: "https://t.me/zyfxlnn", desc: "" },
    { id: "1060", name: "彭于晏iOS破解讨论交流", url: "https://t.me/plus8889", desc: "" },
    { id: "1061", name: "iOS破解插件分享", url: "https://t.me/iparxwy", desc: "" },
    { id: "1046", name: "ios白嫖资源分享 Chat", url: "https://t.me/iosjl_AHKJ", desc: "" },
    { id: "1074", name: "小白菜·iOS游戏分享中心", url: "https://t.me/xiaobaicaifx", desc: "" },
    { id: "1072", name: "巨魔商店 Pro", url: "https://t.me/TrollStorePro", desc: "" },
    { id: "1036", name: "免费白嫖｜破解游戏", url: "https://t.me/svip660", desc: "" },
    { id: "1054", name: "IOS 大杂烩", url: "https://t.me/IOSGAN", desc: "" },
    { id: "1073", name: "宝藏巨魔软件交流群", url: "https://t.me/chatrxwy", desc: "" },
    { id: "1069", name: "曹老板白嫖分享社", url: "https://t.me/clbfxs", desc: "" },
    { id: "1056", name: "秋月资源分享社-软件|辅助", url: "https://t.me/qiuyuezt", desc: "" },
    { id: "1052", name: "ios插件仓库", url: "https://t.me/iosck_AHKJ", desc: "" },
    { id: "1066", name: "苓妹妹ios资源分享", url: "https://t.me/iosfulishare", desc: "" },
    { id: "1062", name: "ipa hack iPhone | iOS", url: "https://t.me/mihalsanch", desc: "" },
    { id: "1057", name: "叮当猫iOS资源/脚本频道", url: "https://t.me/chxm1023", desc: "" },
    { id: "1068", name: "Geek丨iOS软件分享", url: "https://t.me/Geek_iOS", desc: "" },
    { id: "1051", name: "油油资源分享", url: "https://t.me/youyousharechannel", desc: "" },
    { id: "1055", name: "TikTok资源分享", url: "https://t.me/tikdw", desc: "" },
    { id: "1065", name: "羊村资源分享社", url: "https://t.me/qwjhfx", desc: "" },
    { id: "1071", name: "胖虎の交流群", url: "https://t.me/gitbig_chat", desc: "" },
  ],
  "在线配色": [
    { id: "181", name: "vanschneider", url: "http://www.vanschneider.com/colors", desc: "Color Claim was created in 2012 by Tobias van Schneider with the goal to collect & combine unique colors for my future projects." },
    { id: "177", name: "Adobe Color CC", url: "https://color.adobe.com/zh/create/color-wheel", desc: "Create color schemes with the color wheel or browse thousands of color combinations from the Color community." },
    { id: "171", name: "webgradients", url: "https://webgradients.com", desc: "WebGradients is a free collection of 180 linear gradients that you can use as content backdrops in any part of your website." },
    { id: "180", name: "klart", url: "https://klart.co/colors", desc: "Beautiful colors and designs to your inbox every week" },
    { id: "170", name: "Coolest", url: "https://webkul.github.io/coolhue", desc: "Coolest handpicked Gradient Hues for your next super ⚡ amazing stuff" },
    { id: "175", name: "coolors", url: "https://coolors.co", desc: "The super fast color schemes generator!" },
    { id: "169", name: "gradients", url: "http://gradients.io", desc: "Curated gradients for designers and developers" },
    { id: "179", name: "trianglify", url: "http://qrohlf.com/trianglify-generator", desc: "Trianglify Generator" },
    { id: "176", name: "colorhunt", url: "http://www.colorhunt.co", desc: "Beautiful Color Palettes" },
    { id: "168", name: "uigradients", url: "https://uigradients.com", desc: "Beautiful colored gradients" },
    { id: "178", name: "flatui color picker", url: "http://www.flatuicolorpicker.com", desc: "Best Flat Colors For UI Design" },
    { id: "174", name: "flatuicolors", url: "http://flatuicolors.com", desc: "Copy Paste Color Pallette from Flat UI Theme" },
    { id: "172", name: "grabient", url: "https://www.grabient.com", desc: "2017 Grabient by unfold" },
    { id: "173", name: "thedayscolor", url: "http://www.thedayscolor.com", desc: "The daily color digest" },
    { id: "167", name: "khroma", url: "http://khroma.co/generator", desc: "Khroma is the fastest way to discover, search, and save color combos you'll want to use." },
  ],
  "平面素材": [
    { id: "241", name: "图虫图库", url: "https://stock.tuchong.com", desc: "海量图库,涵盖创意图片和矢量素材等" },
    { id: "73", name: "素材搜索", url: "http://so.ui001.com", desc: "设计素材搜索聚合" },
    { id: "64", name: "wallhalla", url: "https://wallhalla.com", desc: "Find awesome high quality wallpapers for desktop and mobile in one place." },
    { id: "74", name: "PS饭团网", url: "http://psefan.com", desc: "不一样的设计素材库！让自己的设计与众不同！" },
    { id: "68", name: "千库网", url: "http://588ku.com", desc: "免费png图片背景素材下载" },
    { id: "75", name: "素材中国", url: "http://www.sccnn.com", desc: "免费素材共享平台" },
    { id: "70", name: "90设计", url: "http://90sheji.com", desc: "电商设计（淘宝美工）千图免费淘宝素材库" },
    { id: "71", name: "昵图网", url: "http://www.nipic.com", desc: "原创素材共享平台" },
    { id: "67", name: "千图网", url: "http://www.58pic.com", desc: "专注免费设计素材下载的网站" },
    { id: "72", name: "懒人图库", url: "http://www.lanrentuku.com", desc: "懒人图库专注于提供网页素材下载" },
    { id: "707", name: "快图网", url: "http://www.kuaipng.com", desc: "快图网提供免费的PNG元素和高清背景图片素材免费下载" },
    { id: "69", name: "我图网", url: "http://www.ooopic.com", desc: "我图网,提供图片素材及模板下载,专注正版设计作品交易" },
    { id: "66", name: "Medialoot", url: "https://medialoot.com", desc: "Free & Premium Design Resources — Medialoot" },
    { id: "63", name: "freepik", url: "https://www.freepik.com", desc: "More than a million free vectors, PSD, photos and free icons." },
    { id: "65", name: "365PSD", url: "https://365psd.com", desc: "Free PSD & Graphics, Illustrations" },
  ],
  "摄影图库": [
    { id: "135", name: "lifeofpix", url: "http://www.lifeofpix.com", desc: "Free high resolution photography" },
    { id: "133", name: "gratisography", url: "https://gratisography.com", desc: "Free high-resolution pictures you can use on your personal and commercial projects, free of copyright restrictions." },
    { id: "131", name: "freenaturestock", url: "http://freenaturestock.com", desc: "Exclusive mindblowing freebies for designers and developers" },
    { id: "120", name: "librestock", url: "https://librestock.com", desc: "65,084 high quality do-what-ever-you-want stock photos" },
    { id: "142", name: "publicdomainarchive", url: "http://publicdomainarchive.com", desc: "New 100% Free Stock Photos. Every. Single. Week." },
    { id: "139", name: "magdeleine", url: "https://magdeleine.co/browse", desc: "HAND-PICKED FREE PHOTOS FOR YOUR INSPIRATION" },
    { id: "130", name: "thestocks", url: "http://thestocks.im", desc: "Use our FREE photos to tell your story!" },
    { id: "347", name: "图图ACG", url: "https://tupian.gq", desc: "致力于分享全网高清好看的图片" },
    { id: "134", name: "imcreator", url: "http://imcreator.com/free", desc: "A curated collection of free web design resources, all for commercial use." },
    { id: "119", name: "visualhunt", url: "https://visualhunt.com", desc: "100% Free High Quality Photos" },
    { id: "122", name: "SplitShire", url: "https://www.splitshire.com", desc: "Free Stock Photos and Videos for commercial use." },
    { id: "121", name: "pixabay", url: "https://pixabay.com", desc: "可在任何地方使用的免费图片和视频" },
    { id: "123", name: "StockSnap", url: "https://stocksnap.io", desc: "Beautiful free stock photos" },
    { id: "128", name: "stokpic", url: "http://stokpic.com", desc: "Free Stock Photos For Commercial Use" },
    { id: "136", name: "skitterphoto", url: "https://skitterphoto.com", desc: "Free Stock Photos for Creative Professionals" },
    { id: "138", name: "skitterphoto", url: "https://skitterphoto.com", desc: "a place to find, show and share public domain photos" },
    { id: "125", name: "myphotopack", url: "https://myphotopack.com", desc: "A free photo pack just for you. Every month." },
    { id: "140", name: "jeshoots", url: "http://jeshoots.com", desc: "New Free Photos & Mockups in to your Inbox!" },
    { id: "118", name: "Unsplash", url: "https://unsplash.com", desc: "Beautiful, free photos." },
    { id: "126", name: "Notaselfie", url: "http://notaselfie.com", desc: "Photos that happen along the way. You can use the images anyway you like. Have fun!" },
  ],
  "iOS捷径": [
    { id: "970", name: "快捷指令库", url: "https://www.rcuts.com", desc: "快捷指令库（rcuts.com）专注分享苹果手机iOS快捷指令大全，提供实用的iPhone快捷指令下载与教程，快捷指令又名iOS捷径，是苹果为iPhone及iPad推出的一款效率工具。" },
    { id: "975", name: "少数派", url: "https://sspai.com/page/playbook/zh-CN", desc: "少数派致力于更好地运用数字产品或科学方法，帮助用户提升工作效率和生活品质" },
    { id: "969", name: "捷径指令大全分享频道", url: "https://t.me/qingtianwe", desc: "" },
    { id: "972", name: "ShortcutsGallery.com", url: "https://shortcutsgallery.com", desc: "Download powerful Siri Shortcuts from others or share the ones you created with the world. These shortcuts will boost your iOS experience." },
    { id: "976", name: "爱捷径", url: "https://www.ijiejing.com", desc: "爱捷径是一个分享苹果快捷指令规则的网站。快捷指令又名iOS捷径，是苹果为iPhone及iPad推出的一款效率工具。可以帮助你高效地完成各种任务。爱捷径收集了许多实用和创新的快捷指令，你可以在这里发现最新的功能和构建技巧。只需在捷径库中点击“获取捷径”，即可将你喜欢的快捷指令添加到你的iOS设备上使用。" },
    { id: "968", name: "捷径库", url: "https://jiejingku.net", desc: "捷径库是苹果快捷指令规则的分享网站。快捷指令是Apple官方出品的iPhone内置效率应用，通过快捷指令可以快捷高效的完成多项任务。捷径库精选了一系列富有创意且实用的快捷指令，探索捷径库可获取快捷指令的最新功能和构建方式。在捷径库中轻点「获取捷径」即可将快捷指令添加到iOS设备中使用。" },
    { id: "966", name: "柯基捷径库", url: "https://www.kejicut.com", desc: "柯基捷径库（www.kejicut.com）专注分享苹果iOS快捷指令与教程,提供高质量iOS捷径,快捷指令原名workflow又名捷径,苹果生态iPhone/iPad/Mac中的一款效率软件。" },
    { id: "977", name: "快捷指令合集", url: "https://hejicut.com", desc: "快捷指令合集（hejicut.com）专注分享iOS快捷指令规则。" },
    { id: "973", name: "实况捷径", url: "https://jiejing.fun", desc: "实况捷径 - 一键转换网络内容和本地媒体为 Live Photo 实况图" },
    { id: "965", name: "iPhone 吧", url: "https://iphone8.vip", desc: "小良,捷径,规则,脚本,解析,应用,教程,下载,快捷指令,Shortcuts,pin脚本,jsbox脚本" },
    { id: "974", name: "奇迹秀", url: "https://www.qijishow.com/Brand/Brand69/index.html", desc: "奇迹秀是一个公益组织，为设计师提供设计干货及资源，站内所有收集的资源都能免费下载，且资源都经过组织成员测试后再发布，保证资源绿色，大家可放心使用，" },
    { id: "967", name: "ShortcutsGallery.com", url: "https://shortcutsgallery.com", desc: "Download powerful Siri Shortcuts from others or share the ones you created with the world. These shortcuts will boost your iOS experience." },
    { id: "964", name: "MacStories", url: "https://www.macstories.net/shortcuts", desc: "Apple news, app reviews, and stories by Federico Viticci and friends." },
    { id: "971", name: "Archive", url: "https://sharecuts.app", desc: "A collection of shortcuts for iOS." },
  ],
  "IOS签名工具": [
    { id: "979", name: "万能签", url: "https://sign.wnqapp.com/ios/indexes.php", desc: "万能签 最新版本7.9.1 大小5.85MB 适用于iOS12以上所有iPhone/iPad。应用信息：一款适用于iOS端IPA的签名注入开发调试工具，所有功能完全免费。支持一键签署多开APP，一键注入移除动态库等，可脱离联网使用，在线安装无需电脑，严禁签名外挂应用及违规APP。" },
    { id: "978", name: "全能签", url: "https://udid.nuosike.cn/sign", desc: "诺思客越狱工具定制签名在线安装" },
    { id: "982", name: "牛蛙助手", url: "https://ios222.com", desc: "牛蛙助手官网-牛蛙助手是一款专业的ios移动端必备的工具，牛蛙助手免费为苹果用户提供：ios移动端免越狱使用apple id签名，ios移动端免越狱全局修改gps定位信息,牛蛙,牛蛙助手,ios222,牛蛙神器" },
    { id: "980", name: "NB全能助手", url: "https://nbtool8.com", desc: "NB全能助手(原NB助手)" },
    { id: "988", name: "TrollStore 2", url: "https://trollstore.app", desc: "TrollStore 2 in a permasigned jailed app that can permanently install any IPA you open in it." },
    { id: "981", name: "爱思助手", url: "https://www.i4.cn", desc: "爱思助手官网-爱思助手是一款专业的苹果刷机助手、苹果越狱助手，专为苹果用户提供百万iPhone、iPad软件、游戏、铃声、壁纸资源安全快速免费下载。" },
    { id: "985", name: "Sideloadly", url: "https://sideloadly.io", desc: "Sideloadly is a tool for sideloading apps on iOS, Apple Silicon Macs, and Apple TV without jailbreak. Download now for a secure and easy sideloading experience." },
    { id: "983", name: "PlayCover", url: "https://playcover.io", desc: "PlayCover allows you to run iOS apps and games natively with keymapping on your Apple Silicon Mac!" },
    { id: "987", name: "GBox", url: "https://gbox.run", desc: "GBox is a professional iOS signing and testing tool, supporting systems from iOS 12.0 to 26. It offers functions such as IPA resigning and app installation testing, allowing you to complete the signing and installation process without the need for a computer. It also supports installation via TrollStore." },
  ],
  "iOS网站": [
    { id: "1023", name: "苹果软件库", url: "https://ios.cuiun.cc/app", desc: "苹果AppStore付费游戏应用共享，致力于分享 iOS 付费软件资源下载和分享，包括游戏共享 ID、软件应用共享 ID等资源的分享和下载，做最稳定最优秀的 iOS 付费游戏/软件共享网站。" },
    { id: "1026", name: "十三资源库", url: "https://tool.joia.cn", desc: "十三资源库，专属于果粉的工具箱. From JoiHouse钟意小屋" },
    { id: "1028", name: "吾爱苹果账号网", url: "https://www.52appleid.com", desc: "为大家分享苹果iOS付费游戏、应用已购账号,免费分享最新的外区苹果共享账号,主要有美国、日本、韩国、香港、台湾地区等海外Apple ID免费分享!" },
    { id: "1029", name: "APPID免费分享", url: "https://appdb.to", desc: "Independent marketplace for iOS, iPadOS, MacOS, Apple devices. Publish your apps for free independently. Install apps that you want securely and privately. - appdb" },
    { id: "1027", name: "林先生苹果工具箱", url: "https://lin.mrlin.vip", desc: "林先生苹果工具箱" },
    { id: "1018", name: "神科技工具页", url: "https://ai.id64.com/index.aspx", desc: "" },
    { id: "1015", name: "挂神团队", url: "https://app.nk8686.com", desc: "挂神团队" },
    { id: "1016", name: "威锋", url: "https://www.feng.com", desc: "威锋，千万果粉大本营，是中文苹果用户首选的苹果媒体及苹果社区。来威锋，看苹果资讯、讨论当下科技热点、分享玩机心得、优惠购买苹果产品、参与科技酷品试玩活动，获得更多苹果服务。威锋提供7*24小时的苹果资讯，科技原创观点、Apple软硬件、智能硬件评测等，涵盖Apple的iPhone、Mac、iPad、Apple Watch等全系列产品及周边。威锋社区犹如宝藏，沉淀了几亿个关于苹果系统（macOS、iOS）、插件软件壁纸游戏资源、玩机技巧、开箱晒货、摄影、配件硬件等与苹果科技相关的分享讨论。" },
    { id: "1000", name: "玄烨品果", url: "https://dkxuanye.cn", desc: "" },
    { id: "1013", name: "异次元软件世界", url: "https://www.iplaysoft.com/os/ios-platform", desc: "极具人气和特色的软件网站！专注于推荐优秀软件、APP应用和互联网资源，每篇图文评测都极其用心，并提供大量软件资源下载。" },
    { id: "1011", name: "蘋果iPhone", url: "https://mrmad.com.tw", desc: "提供最新蘋果、iPhone、iPad、Apple Watch、Mac和3C科技資訊，以專業經驗免費與大家分享。" },
    { id: "1032", name: "Decrypt IPA Store", url: "https://decrypt.day", desc: "Just a moment..." },
    { id: "1019", name: "微信美化", url: "https://soda-ldz.yourepo.com", desc: "" },
    { id: "1030", name: "玩机大学", url: "https://www.cccitu.com/cat/ios", desc: "CCCiTU 玩机大学 - 只玩干货教程" },
    { id: "1025", name: "misaka", url: "https://github.com/straight-tamago/misaka", desc: "" },
    { id: "1022", name: "Apple (中国大陆)", url: "https://www.apple.com.cn", desc: "探索 Apple 的创新世界，选购各式 iPhone、iPad、Apple Watch 和 Mac，浏览各类配件、娱乐产品，并获得相关产品的专家服务支持。" },
    { id: "1003", name: "苹果系统固件查询与下载", url: "https://ipsw.me", desc: "Download current and previous versions of Apple's iOS, iPadOS, watchOS, tvOS, audioOS and macOS firmware and receive notifications when new firmwares are released." },
    { id: "999", name: "TutuApp VIP", url: "https://github.com/opa334/Dopamine", desc: "Join the world's most widely adopted, AI-powered developer platform where millions of developers, businesses, and the largest open source community build software that advances humanity." },
    { id: "1020", name: "越狱论坛", url: "https://whyjailbreak.com", desc: "" },
    { id: "1021", name: "依赖查询网址", url: "https://www.ios-repo-updates.com", desc: "Cydia iOS Repository Updates for Jailbroken iPhone iPad or iPod" },
  ],
  "Chrome插件": [
    { id: "189", name: "wappalyzer", url: "https://www.wappalyzer.com", desc: "Identify technology on websites" },
    { id: "192", name: "csspeeper", url: "https://csspeeper.com", desc: "Smart CSS viewer tailored for Designers." },
    { id: "190", name: "Panda", url: "http://usepanda.com", desc: "A smart news reader built for productivity." },
    { id: "191", name: "sizzy", url: "https://sizzy.co", desc: "A tool for developing responsive websites crazy-fast" },
    { id: "194", name: "mustsee", url: "http://mustsee.earth", desc: "Discover the world's most beautiful places at every opened tab." },
  ],
};
