// 甜甜导航 - 站点数据（自动生成）
export interface Site {
  id: string;
  name: string;
  url: string;
  desc: string;
  icon?: string;
}

export const categories_part1: Record<string, Site[]> = {
  "iOS网盘": [
    { id: "887", name: "甜甜网盘", url: "https://pan.puaaa.cn", desc: "甜甜网盘iOS资源网盘分享" },
    { id: "928", name: "宅哥技术网盘", url: "https://pan.312752.cn", desc: "宅哥技术网盘iOS资源网盘分享" },
    { id: "931", name: "IPA分享站", url: "https://pan.cjq6525.xyz", desc: "IPA分享站iOS资源网盘分享" },
    { id: "925", name: "91网盘", url: "https://alist.91ios.fun", desc: "91网盘iOS资源网盘分享" },
    { id: "935", name: "DaPeng网盘", url: "https://wp.sha0p.cn", desc: "DaPeng网盘iOS资源网盘分" },
    { id: "930", name: "IOS神器", url: "https://iossq.top", desc: "IOS神器iOS资源网盘分享" },
    { id: "923", name: "平凡", url: "https://pan.iosi.vip", desc: "平凡iOS资源网盘分享" },
    { id: "905", name: "小海网盘", url: "https://pan.weblyc.cn", desc: "小海网盘iOS资源网盘分享" },
    { id: "912", name: "鹏客网盘", url: "https://peck.cool", desc: "鹏客网盘iOS资源网盘分享" },
    { id: "932", name: "薛萌萌网盘", url: "https://pan.xmmqm.cn", desc: "薛萌萌网盘iOS资源网盘分享" },
    { id: "946", name: "爱锋助手资源盘", url: "https://pan.yhios.cn", desc: "爱锋助手资源盘iOS资源网盘分享" },
    { id: "908", name: "顷酉网盘", url: "https://pan.586226.xyz", desc: "顷酉网盘iOS资源网盘分享" },
    { id: "913", name: "优创网盘", url: "https://pan.ucgod.cn", desc: "优创网盘iOS资源网盘分享" },
    { id: "924", name: "小艾网盘", url: "http://dh.agxmt.com", desc: "小艾网盘iOS资源网盘分享" },
    { id: "927", name: "萌仙科技网盘", url: "https://pan.mxwlcm.cn", desc: "萌仙科技网盘iOS资源网盘分享" },
    { id: "926", name: "知网云盘", url: "https://pan.xyyh.xyz", desc: "知网云盘iOS资源网盘分享" },
    { id: "914", name: "酷乐网盘", url: "https://pan.6789o.com", desc: "酷乐网盘iOS资源网盘分享" },
    { id: "899", name: "DumpApp", url: "https://pan.dumpapp.com", desc: "DumpAppiOS资源网盘分享" },
    { id: "910", name: "微速云盘", url: "https://pan.iosdz.cn", desc: "微速云盘iOS资源网盘分享" },
    { id: "901", name: "小萝卜云盘", url: "https://yun.lbbb.cc", desc: "小萝卜云盘iOS资源网盘分享" },
    { id: "929", name: "TuziN’s Cloud", url: "https://pan.drophere.info", desc: "TuziN’s CloudiOS" },
    { id: "917", name: "晴天网盘", url: "https://alist.jiejingfan.vip", desc: "晴天网盘iOS资源网盘分享" },
    { id: "944", name: "兔兔网盘", url: "https://alist.tooios.com", desc: "兔兔网盘iOS资源网盘分享" },
    { id: "904", name: "奇心网盘", url: "https://pan.qxnav.com", desc: "奇心网盘iOS资源网盘分享" },
    { id: "922", name: "壹筒云盘", url: "https://pan.yttxcs.com", desc: "壹筒云盘iOS资源网盘分享" },
    { id: "945", name: "ios砸壳分享网", url: "https://pan.lhd8.cn", desc: "ios砸壳分享网iOS资源网盘分" },
    { id: "920", name: "皮卡丘网盘", url: "https://pan.pkq7.cn", desc: "皮卡丘网盘iOS资源网盘分享" },
    { id: "907", name: "瑞创云盘", url: "https://pan.qx7c.cn", desc: "瑞创云盘iOS资源网盘分享" },
    { id: "919", name: "黑猫网盘", url: "https://xn--z7x144g.club", desc: "黑猫网盘iOS资源网盘分享" },
    { id: "916", name: "iOS宝藏", url: "https://pan.iosrxwy.com", desc: "iOS宝藏iOS资源网盘分享" },
    { id: "1017", name: "蒲公英", url: "https://www.pgyer.com", desc: "应用内测分发平台" },
    { id: "921", name: "一天云", url: "https://bytian.vip", desc: "一天云iOS资源网盘分享" },
    { id: "918", name: "小鹿", url: "https://ipa.p12.pp.ua", desc: "小鹿iOS资源网盘分享" },
    { id: "911", name: "小昕资源网盘", url: "https://pan.iosxin.top", desc: "小昕资源网盘iOS资源网盘分享" },
    { id: "909", name: "ios资源分享", url: "https://pan.iosku.top", desc: "ios资源分享iOS资源网盘分享" },
    { id: "947", name: "柒吾网盘", url: "https://ipa.zhou75.cn", desc: "柒吾网盘iOS资源网盘分享" },
    { id: "900", name: "小熊", url: "https://pan.v200dd.top", desc: "小熊iOS资源网盘分享" },
    { id: "915", name: "An南拥夏栀", url: "https://share.nyxz166.com", desc: "An南拥夏栀iOS资源网盘分享" },
    { id: "903", name: "爱转发网盘", url: "https://pan.wxazf.com", desc: "爱转发网盘iOS资源网盘分享" },
    { id: "902", name: "叶子库网盘", url: "https://pan.yeziku.cn", desc: "叶子库网盘iOS资源网盘分享" },
  ],
  "iOS捷径": [
    { id: "970", name: "快捷指令库", url: "https://www.rcuts.com", desc: "快捷指令库iOS快捷指令资源" },
    { id: "975", name: "少数派", url: "https://sspai.com/page/playbook/zh-CN", desc: "少数派iOS快捷指令资源" },
    { id: "969", name: "捷径指令大全分享频道", url: "https://t.me/qingtianwe", desc: "捷径指令大全分享频道iOS快捷指" },
    { id: "972", name: "ShortcutsGallery.com", url: "https://shortcutsgallery.com", desc: "ShortcutsGallery" },
    { id: "976", name: "爱捷径", url: "https://www.ijiejing.com", desc: "爱捷径iOS快捷指令资源" },
    { id: "968", name: "捷径库", url: "https://jiejingku.net", desc: "捷径库iOS快捷指令资源" },
    { id: "966", name: "柯基捷径库", url: "https://www.kejicut.com", desc: "柯基捷径库iOS快捷指令资源" },
    { id: "977", name: "快捷指令合集", url: "https://hejicut.com", desc: "快捷指令合集iOS快捷指令资源" },
    { id: "973", name: "实况捷径", url: "https://jiejing.fun", desc: "实况捷径iOS快捷指令资源" },
    { id: "965", name: "iPhone 吧", url: "https://iphone8.vip", desc: "iPhone 吧iOS快捷指令资" },
    { id: "974", name: "奇迹秀", url: "https://www.qijishow.com/Brand/Brand69/index.html", desc: "奇迹秀iOS快捷指令资源" },
    { id: "967", name: "ShortcutsGallery.com", url: "https://shortcutsgallery.com", desc: "ShortcutsGallery" },
    { id: "964", name: "MacStories", url: "https://www.macstories.net/shortcuts", desc: "MacStoriesiOS快捷指" },
    { id: "971", name: "Archive", url: "https://sharecuts.app", desc: "ArchiveiOS快捷指令资源" },
  ],
  "IOS签名工具": [
    { id: "979", name: "万能签", url: "https://sign.wnqapp.com/ios/indexes.php", desc: "万能签iOS签名工具站" },
    { id: "978", name: "全能签", url: "https://udid.nuosike.cn/sign", desc: "全能签iOS签名工具站" },
    { id: "982", name: "牛蛙助手", url: "https://ios222.com", desc: "牛蛙助手iOS签名工具站" },
    { id: "980", name: "NB全能助手", url: "https://nbtool8.com", desc: "NB全能助手iOS签名工具站" },
    { id: "988", name: "TrollStore 2", url: "https://trollstore.app", desc: "TrollStore 2iOS签" },
    { id: "981", name: "爱思助手", url: "https://www.i4.cn", desc: "爱思助手iOS签名工具站" },
    { id: "985", name: "Sideloadly", url: "https://sideloadly.io", desc: "SideloadlyiOS签名工" },
    { id: "983", name: "PlayCover", url: "https://playcover.io", desc: "PlayCoveriOS签名工具" },
    { id: "987", name: "GBox", url: "https://gbox.run", desc: "GBoxiOS签名工具站" },
  ],
  "iOS网站": [
    { id: "1023", name: "苹果软件库", url: "https://ios.cuiun.cc/app", desc: "iOS应用资源库" },
    { id: "1026", name: "十三资源库", url: "https://tool.joia.cn", desc: "十三资源库iOS资源相关网站" },
    { id: "1028", name: "吾爱苹果账号网", url: "https://www.52appleid.com", desc: "吾爱苹果账号网iOS资源相关网站" },
    { id: "1029", name: "APPID免费分享", url: "https://appdb.to", desc: "APPID免费分享iOS资源相关" },
    { id: "1027", name: "林先生苹果工具箱", url: "https://lin.mrlin.vip", desc: "林先生苹果工具箱iOS资源相关网" },
    { id: "1018", name: "神科技工具页", url: "https://ai.id64.com/index.aspx", desc: "神科技工具页iOS资源相关网站" },
    { id: "1015", name: "挂神团队", url: "https://app.nk8686.com", desc: "挂神团队iOS资源相关网站" },
    { id: "1016", name: "威锋", url: "https://www.feng.com", desc: "果粉交流社区" },
    { id: "1000", name: "玄烨品果", url: "https://dkxuanye.cn", desc: "玄烨品果iOS资源相关网站" },
    { id: "1013", name: "异次元软件世界", url: "https://www.iplaysoft.com/os/ios-platform", desc: "软件评测与分享" },
    { id: "1011", name: "蘋果iPhone", url: "https://mrmad.com.tw", desc: "蘋果iPhoneiOS资源相关网" },
    { id: "1032", name: "Decrypt IPA Store", url: "https://decrypt.day", desc: "Decrypt IPA Stor" },
    { id: "1019", name: "微信美化", url: "https://soda-ldz.yourepo.com", desc: "微信美化iOS资源相关网站" },
    { id: "1030", name: "玩机大学", url: "https://www.cccitu.com/cat/ios", desc: "玩机大学iOS资源相关网站" },
    { id: "1025", name: "misaka", url: "https://github.com/straight-tamago/misaka", desc: "misakaiOS资源相关网站" },
    { id: "1022", name: "Apple (中国大陆)", url: "https://www.apple.com.cn", desc: "苹果中国官网" },
    { id: "1003", name: "苹果系统固件查询与下载", url: "https://ipsw.me", desc: "苹果系统固件查询与下载iOS资源" },
    { id: "999", name: "TutuApp VIP", url: "https://github.com/opa334/Dopamine", desc: "TutuApp VIPiOS资源" },
    { id: "1020", name: "越狱论坛", url: "https://whyjailbreak.com", desc: "越狱论坛iOS资源相关网站" },
    { id: "1021", name: "依赖查询网址", url: "https://www.ios-repo-updates.com", desc: "依赖查询网址iOS资源相关网站" },
    { id: "1002", name: "Betahub.cn", url: "https://betahub.cn", desc: "Betahub.cniOS资源相" },
    { id: "1012", name: "ios Libray", url: "https://iosninja.io/ipa-library-ios", desc: "ios LibrayiOS资源相" },
    { id: "1024", name: "TrollInstallerX", url: "https://hgithub.xyz/alfiecg24/TrollInstallerX/releases", desc: "TrollInstallerXi" },
    { id: "1014", name: "SHIDU", url: "https://zwjpai.com", desc: "SHIDUiOS资源相关网站" },
    { id: "1031", name: "jailbreak", url: "https://silzee.com", desc: "jailbreakiOS资源相关" },
    { id: "1001", name: "CoolStar’s Website", url: "https://coolstar.org/electra", desc: "CoolStar’s Websi" },
    { id: "new_iOS网站_26", name: "pan.ios98.com", url: "https://pan.ios98.com", desc: "iOS资源网盘分享" },
    { id: "new_iOS网站_27", name: "3web", url: "https://3web.top", desc: "IPA应用下载站" },
    { id: "new_iOS网站_28", name: "TrollStore官网", url: "https://trollstoreapp.com", desc: "巨魔商店官方" },
    { id: "new_iOS网站_29", name: "ios.cfw.guide", url: "https://ios.cfw.guide", desc: "iOS越狱安装指南" },
  ],
  "TG资源": [
    { id: "1070", name: "资源分享客栈-Applnn", url: "https://t.me/zyfxlnn", desc: "资源分享客栈-ApplnnTel" },
    { id: "1060", name: "彭于晏iOS破解讨论交流", url: "https://t.me/plus8889", desc: "彭于晏iOS破解讨论交流Tele" },
    { id: "1061", name: "iOS破解插件分享", url: "https://t.me/iparxwy", desc: "iOS破解插件分享Telegra" },
    { id: "1046", name: "ios白嫖资源分享 Chat", url: "https://t.me/iosjl_AHKJ", desc: "ios白嫖资源分享 ChatTe" },
    { id: "1074", name: "小白菜·iOS游戏分享中心", url: "https://t.me/xiaobaicaifx", desc: "小白菜·iOS游戏分享中心Tel" },
    { id: "1072", name: "巨魔商店 Pro", url: "https://t.me/TrollStorePro", desc: "巨魔商店 ProTelegram" },
    { id: "1036", name: "免费白嫖｜破解游戏", url: "https://t.me/svip660", desc: "免费白嫖｜破解游戏Telegra" },
    { id: "1054", name: "IOS 大杂烩🇨🇳", url: "https://t.me/IOSGAN", desc: "IOS 大杂烩🇨🇳Telegra" },
    { id: "1073", name: "宝藏巨魔软件交流群", url: "https://t.me/chatrxwy", desc: "宝藏巨魔软件交流群Telegra" },
    { id: "1069", name: "曹老板白嫖分享社", url: "https://t.me/clbfxs", desc: "曹老板白嫖分享社Telegram" },
    { id: "1056", name: "秋月资源分享社-软件|辅助", url: "https://t.me/qiuyuezt", desc: "秋月资源分享社-软件|辅助Tel" },
    { id: "1052", name: "ios插件仓库", url: "https://t.me/iosck_AHKJ", desc: "ios插件仓库Telegram资" },
    { id: "1066", name: "苓妹妹ios资源分享", url: "https://t.me/iosfulishare", desc: "苓妹妹ios资源分享Telegr" },
    { id: "1062", name: "ipa hack iPhone | iOS", url: "https://t.me/mihalsanch", desc: "ipa hack iPhone " },
    { id: "1057", name: "叮当猫iOS资源/脚本频道", url: "https://t.me/chxm1023", desc: "叮当猫iOS资源/脚本频道Tel" },
    { id: "1068", name: "Geek丨iOS软件分享", url: "https://t.me/Geek_iOS", desc: "Geek丨iOS软件分享Tele" },
    { id: "1051", name: "油油资源分享", url: "https://t.me/youyousharechannel", desc: "油油资源分享Telegram资源" },
    { id: "1055", name: "TikTok资源分享", url: "https://t.me/tikdw", desc: "TikTok资源分享Telegr" },
    { id: "1065", name: "羊村资源分享社", url: "https://t.me/qwjhfx", desc: "羊村资源分享社Telegram资" },
    { id: "1071", name: "胖虎の交流群", url: "https://t.me/gitbig_chat", desc: "胖虎の交流群Telegram资源" },
    { id: "1053", name: "iOS IPA分享『时光』", url: "https://t.me/IOSIPAFX", desc: "iOS IPA分享『时光』Tel" },
    { id: "1067", name: "PKC皮卡车", url: "https://t.me/TopStyle2021", desc: "PKC皮卡车Telegram资源" },
    { id: "1047", name: "秋名山巨魔交流群", url: "https://t.me/ae86Chat", desc: "秋名山巨魔交流群Telegram" },
    { id: "1064", name: "ios玩机交流", url: "https://t.me/IOSwanji", desc: "ios玩机交流Telegram资" },
    { id: "1048", name: "iOS 越狱巨魔玩家", url: "https://t.me/iosjumo", desc: "iOS 越狱巨魔玩家Telegr" },
    { id: "1063", name: "刀刀源", url: "https://t.me/ae86_hk", desc: "刀刀源Telegram资源导航" },
    { id: "1044", name: "IPA ios", url: "https://t.me/privateipa", desc: "IPA iosTelegram资" },
    { id: "1059", name: "JwipaS｜Original IPA | Dump", url: "https://t.me/JwipaS", desc: "JwipaS｜Original " },
    { id: "1041", name: "ios软件分享", url: "https://t.me/iOSappIPA", desc: "ios软件分享Telegram资" },
    { id: "1050", name: "魔法少女️️⚝伊蕾娜️", url: "https://t.me/ElnSAMA", desc: "魔法少女️️⚝伊蕾娜️Teleg" },
    { id: "1042", name: "ios鸡神-专注分享破解", url: "https://t.me/gjwj6", desc: "ios鸡神-专注分享破解Tele" },
    { id: "1058", name: "iOS[🅡星]交流", url: "https://t.me/TrollstoreMios", desc: "iOS[🅡星]交流Telegra" },
    { id: "1049", name: "资源/工具/百科/中文/导航", url: "https://t.me/ecaka", desc: "资源/工具/百科/中文/导航Te" },
    { id: "1045", name: "小新の资源库", url: "https://t.me/xiaoxinv", desc: "小新の资源库Telegram资源" },
    { id: "1034", name: "巨魔资源iOS", url: "https://t.me/Trollstore2ios", desc: "巨魔资源iOSTelegram资" },
    { id: "1033", name: "破解软件资源分享", url: "https://t.me/tkdashen", desc: "破解软件资源分享Telegram" },
    { id: "1037", name: "男神嘿嘿- iOS频道", url: "https://t.me/IPAs_share", desc: "男神嘿嘿- iOS频道Teleg" },
    { id: "1035", name: "苹果iOS破解软件分享", url: "https://t.me/iospj66", desc: "苹果iOS破解软件分享Teleg" },
    { id: "1040", name: "ios个人自用", url: "https://t.me/ios2580", desc: "ios个人自用Telegram资" },
    { id: "1043", name: "iOS优质应用", url: "https://t.me/ioskk", desc: "iOS优质应用Telegram资" },
  ],
  "在线配色": [
    { id: "181", name: "vanschneider", url: "http://www.vanschneider.com/colors", desc: "vanschneider在线配色" },
    { id: "177", name: "Adobe Color CC", url: "https://color.adobe.com/zh/create/color-wheel", desc: "Adobe配色工具" },
    { id: "171", name: "webgradients", url: "https://webgradients.com", desc: "渐变背景库" },
    { id: "180", name: "klart", url: "https://klart.co/colors", desc: "klart在线配色工具" },
    { id: "170", name: "Coolest", url: "https://webkul.github.io/coolhue", desc: "Coolest在线配色工具" },
    { id: "175", name: "coolors", url: "https://coolors.co", desc: "在线配色生成器" },
    { id: "169", name: "gradients", url: "http://gradients.io", desc: "gradients在线配色工具" },
    { id: "179", name: "trianglify", url: "http://qrohlf.com/trianglify-generator", desc: "trianglify在线配色工具" },
    { id: "176", name: "colorhunt", url: "http://www.colorhunt.co", desc: "配色灵感社区" },
    { id: "168", name: "uigradients", url: "https://uigradients.com", desc: "渐变配色生成" },
    { id: "178", name: "flatui color picker", url: "http://www.flatuicolorpicker.com", desc: "flatui color pic" },
    { id: "174", name: "flatuicolors", url: "http://flatuicolors.com", desc: "扁平配色方案" },
    { id: "172", name: "grabient", url: "https://www.grabient.com", desc: "grabient在线配色工具" },
    { id: "173", name: "thedayscolor", url: "http://www.thedayscolor.com", desc: "thedayscolor在线配色" },
    { id: "167", name: "khroma", url: "http://khroma.co/generator", desc: "AI配色生成器" },
    { id: "new_在线配色_15", name: "ColorSpace", url: "https://mycolor.space", desc: "渐变色自动生成" },
  ],
  "Chrome插件": [
    { id: "189", name: "wappalyzer", url: "https://www.wappalyzer.com", desc: "wappalyzerChrome" },
    { id: "192", name: "csspeeper", url: "https://csspeeper.com", desc: "csspeeperChrome浏" },
    { id: "190", name: "Panda", url: "http://usepanda.com", desc: "PandaChrome浏览器插件" },
    { id: "191", name: "sizzy", url: "https://sizzy.co", desc: "sizzyChrome浏览器插件" },
    { id: "194", name: "mustsee", url: "http://mustsee.earth", desc: "mustseeChrome浏览器" },
  ],
  "交互动效": [
    { id: "162", name: "Adobe After Effects CC", url: "https://www.adobe.com/cn/products/aftereffects", desc: "Adobe After Effe" },
    { id: "163", name: "principle", url: "http://principleformac.com", desc: "principle交互动效资源" },
    { id: "164", name: "flinto", url: "https://www.flinto.com", desc: "flinto交互动效资源" },
    { id: "166", name: "ProtoPie", url: "http://www.protopie.cn", desc: "高保真交互原型" },
    { id: "165", name: "framer", url: "https://framer.com", desc: "framer交互动效资源" },
  ],
};