// 甜甜导航 - 站点数据（自动生成）
export interface Site {
  id: string;
  name: string;
  url: string;
  desc: string;
  icon?: string;
}

export interface NavGroup {
  id: string;
  name: string;
  icon: string;
  desc: string;
  cats: string[];
}

export const categories: Record<string, Site[]> = {
  "iOS网盘": [
    { id: "887", name: "甜甜网盘", url: "https://pan.puaaa.cn", desc: "免费免费一直免费开放！", icon: "https://iosdh.cn/wp-content/uploads/2025/10/%E7%94%9C%E7%94%9C%E7%BD%91%E7%9B%98icon.svg" },
    { id: "928", name: "宅哥技术网盘", url: "https://pan.312752.cn", desc: "宅哥技术网盘" },
    { id: "931", name: "IPA分享站", url: "https://pan.cjq6525.xyz", desc: "IPA分享站" },
    { id: "925", name: "91网盘", url: "https://alist.91ios.fun", desc: "91网盘-ipa资源网盘" },
    { id: "935", name: "DaPeng网盘", url: "https://wp.sha0p.cn", desc: "DaPeng网盘｜iOS资源分享网-IPA资源库-巨魔商店IPA软件资源-网络资源分享" },
    { id: "930", name: "IOS神器", url: "https://iossq.top", desc: "IOS神器" },
    { id: "923", name: "平凡", url: "https://pan.iosi.vip", desc: "平凡" },
    { id: "905", name: "小海网盘", url: "https://pan.weblyc.cn", desc: "小海资源分享网盘" },
    { id: "912", name: "鹏客网盘", url: "https://peck.cool", desc: "peckios" },
    { id: "932", name: "薛萌萌网盘", url: "https://pan.xmmqm.cn", desc: "薛萌萌网盘" },
    { id: "946", name: "爱锋助手资源盘", url: "https://pan.yhios.cn", desc: "爱锋助手资源盘专注于iOS应用分享，提供免费企业证书、IPA签名包、精品iOS软件与游戏、微信多开插件、IPA安装包、微信主题美化等，支持在线安装与极速下载。" },
    { id: "908", name: "顷酉网盘", url: "https://pan.586226.xyz", desc: "顷酉网盘-为果粉提供的资源站" },
    { id: "913", name: "优创网盘", url: "https://pan.ucgod.cn", desc: "优创网盘 - iuczy优创AppStore" },
    { id: "924", name: "小艾网盘", url: "http://dh.agxmt.com", desc: "小艾网盘" },
    { id: "927", name: "萌仙科技网盘", url: "https://pan.mxwlcm.cn", desc: "萌仙科技网盘" },
    { id: "926", name: "知网云盘", url: "https://pan.xyyh.xyz", desc: "知网云盘" },
    { id: "914", name: "酷乐网盘", url: "https://pan.6789o.com", desc: "酷乐网盘" },
    { id: "899", name: "DumpApp", url: "https://pan.dumpapp.com", desc: "DumpApp" },
    { id: "910", name: "微速云盘", url: "https://pan.iosdz.cn", desc: "微速 云盘" },
    { id: "901", name: "小萝卜云盘", url: "https://yun.lbbb.cc", desc: "小萝卜云盘" },
  ],
  "TG资源": [
    { id: "1070", name: "资源分享客栈-Applnn", url: "https://t.me/zyfxlnn", desc: "" },
    { id: "1060", name: "彭于晏iOS破解讨论交流", url: "https://t.me/plus8889", desc: "" },
    { id: "1061", name: "iOS破解插件分享", url: "https://t.me/iparxwy", desc: "" },
    { id: "1046", name: "ios白嫖资源分享 Chat", url: "https://t.me/iosjl_AHKJ", desc: "" },
    { id: "1074", name: "小白菜·iOS游戏分享中心", url: "https://t.me/xiaobaicaifx", desc: "" },
    { id: "1072", name: "巨魔商店 Pro", url: "https://t.me/TrollStorePro", desc: "" },
    { id: "1036", name: "免费白嫖｜破解游戏", url: "https://t.me/svip660", desc: "" },
    { id: "1054", name: "IOS 大杂烩🇨🇳", url: "https://t.me/IOSGAN", desc: "" },
    { id: "1073", name: "宝藏巨魔软件交流群", url: "https://t.me/chatrxwy", desc: "" },
    { id: "1069", name: "曹老板白嫖分享社", url: "https://t.me/clbfxs", desc: "" },
    { id: "1056", name: "秋月资源分享社-软件|辅助", url: "https://t.me/qiuyuezt", desc: "" },
    { id: "1052", name: "ios插件仓库", url: "https://t.me/iosck_AHKJ", desc: "" },
    { id: "1066", name: "苓妹妹ios资源分享", url: "https://t.me/iosfulishare", desc: "" },
    { id: "1062", name: "ipa hack iPhone | iOS", url: "https://t.me/mihalsanch", desc: "" },
    { id: "1057", name: "叮当猫iOS资源/脚本频道", url: "https://t.me/chxm1023", desc: "" },
    { id: "1068", name: "Geek丨iOS软件分享", url: "https://t.me/Geek_iOS", desc: "" },
    { id: "1051", name: "油油资源分享", url: "https://t.me/youyousharechannel", desc: "" },
    { id: "1055", name: "TikTok资源分享", url: "https://t.me/tikdw", desc: "" },
    { id: "1065", name: "羊村资源分享社", url: "https://t.me/qwjhfx", desc: "" },
    { id: "1071", name: "胖虎の交流群", url: "https://t.me/gitbig_chat", desc: "" },
  ],
  "在线配色": [
    { id: "181", name: "vanschneider", url: "http://www.vanschneider.com/colors", desc: "Color Claim was created in 2012 by Tobias van Schneider with the goal to collect & combine unique colors for my future projects." },
    { id: "177", name: "Adobe Color CC", url: "https://color.adobe.com/zh/create/color-wheel", desc: "Create color schemes with the color wheel or browse thousands of color combinations from the Color community." },
    { id: "171", name: "webgradients", url: "https://webgradients.com", desc: "WebGradients is a free collection of 180 linear gradients that you can use as content backdrops in any part of your website." },
    { id: "180", name: "klart", url: "https://klart.co/colors", desc: "Beautiful colors and designs to your inbox every week" },
    { id: "170", name: "Coolest", url: "https://webkul.github.io/coolhue", desc: "Coolest handpicked Gradient Hues for your next super ⚡ amazing stuff" },
    { id: "175", name: "coolors", url: "https://coolors.co", desc: "The super fast color schemes generator!" },
    { id: "169", name: "gradients", url: "http://gradients.io", desc: "Curated gradients for designers and developers" },
    { id: "179", name: "trianglify", url: "http://qrohlf.com/trianglify-generator", desc: "Trianglify Generator" },
    { id: "176", name: "colorhunt", url: "http://www.colorhunt.co", desc: "Beautiful Color Palettes" },
    { id: "168", name: "uigradients", url: "https://uigradients.com", desc: "Beautiful colored gradients" },
    { id: "178", name: "flatui color picker", url: "http://www.flatuicolorpicker.com", desc: "Best Flat Colors For UI Design" },
    { id: "174", name: "flatuicolors", url: "http://flatuicolors.com", desc: "Copy Paste Color Pallette from Flat UI Theme" },
    { id: "172", name: "grabient", url: "https://www.grabient.com", desc: "2017 Grabient by unfold" },
    { id: "173", name: "thedayscolor", url: "http://www.thedayscolor.com", desc: "The daily color digest" },
    { id: "167", name: "khroma", url: "http://khroma.co/generator", desc: "Khroma is the fastest way to discover, search, and save color combos you'll want to use." },
  ],
  "平面素材": [
    { id: "241", name: "图虫图库", url: "https://stock.tuchong.com", desc: "海量图库,涵盖创意图片和矢量素材等" },
    { id: "73", name: "素材搜索", url: "http://so.ui001.com", desc: "设计素材搜索聚合" },
    { id: "64", name: "wallhalla", url: "https://wallhalla.com", desc: "Find awesome high quality wallpapers for desktop and mobile in one place." },
    { id: "74", name: "PS饭团网", url: "http://psefan.com", desc: "不一样的设计素材库！让自己的设计与众不同！" },
    { id: "68", name: "千库网", url: "http://588ku.com", desc: "免费png图片背景素材下载" },
    { id: "75", name: "素材中国", url: "http://www.sccnn.com", desc: "免费素材共享平台" },
    { id: "70", name: "90设计", url: "http://90sheji.com", desc: "电商设计（淘宝美工）千图免费淘宝素材库" },
    { id: "71", name: "昵图网", url: "http://www.nipic.com", desc: "原创素材共享平台" },
    { id: "67", name: "千图网", url: "http://www.58pic.com", desc: "专注免费设计素材下载的网站" },
    { id: "72", name: "懒人图库", url: "http://www.lanrentuku.com", desc: "懒人图库专注于提供网页素材下载" },
    { id: "707", name: "快图网", url: "http://www.kuaipng.com", desc: "快图网提供免费的PNG元素和高清背景图片素材免费下载" },
    { id: "69", name: "我图网", url: "http://www.ooopic.com", desc: "我图网,提供图片素材及模板下载,专注正版设计作品交易" },
    { id: "66", name: "Medialoot", url: "https://medialoot.com", desc: "Free & Premium Design Resources — Medialoot" },
    { id: "63", name: "freepik", url: "https://www.freepik.com", desc: "More than a million free vectors, PSD, photos and free icons." },
    { id: "65", name: "365PSD", url: "https://365psd.com", desc: "Free PSD & Graphics, Illustrations" },
  ],
  "摄影图库": [
    { id: "135", name: "lifeofpix", url: "http://www.lifeofpix.com", desc: "Free high resolution photography" },
    { id: "133", name: "gratisography", url: "https://gratisography.com", desc: "Free high-resolution pictures you can use on your personal and commercial projects, free of copyright restrictions." },
    { id: "131", name: "freenaturestock", url: "http://freenaturestock.com", desc: "Exclusive mindblowing freebies for designers and developers" },
    { id: "120", name: "librestock", url: "https://librestock.com", desc: "65,084 high quality do-what-ever-you-want stock photos" },
    { id: "142", name: "publicdomainarchive", url: "http://publicdomainarchive.com", desc: "New 100% Free Stock Photos. Every. Single. Week." },
    { id: "139", name: "magdeleine", url: "https://magdeleine.co/browse", desc: "HAND-PICKED FREE PHOTOS FOR YOUR INSPIRATION" },
    { id: "130", name: "thestocks", url: "http://thestocks.im", desc: "Use our FREE photos to tell your story!" },
    { id: "347", name: "图图ACG", url: "https://tupian.gq", desc: "致力于分享全网高清好看的图片" },
    { id: "134", name: "imcreator", url: "http://imcreator.com/free", desc: "A curated collection of free web design resources, all for commercial use." },
    { id: "119", name: "visualhunt", url: "https://visualhunt.com", desc: "100% Free High Quality Photos" },
    { id: "122", name: "SplitShire", url: "https://www.splitshire.com", desc: "Free Stock Photos and Videos for commercial use." },
    { id: "121", name: "pixabay", url: "https://pixabay.com", desc: "可在任何地方使用的免费图片和视频" },
    { id: "123", name: "StockSnap", url: "https://stocksnap.io", desc: "Beautiful free stock photos" },
    { id: "128", name: "stokpic", url: "http://stokpic.com", desc: "Free Stock Photos For Commercial Use" },
    { id: "136", name: "skitterphoto", url: "https://skitterphoto.com", desc: "Free Stock Photos for Creative Professionals" },
    { id: "138", name: "skitterphoto", url: "https://skitterphoto.com", desc: "a place to find, show and share public domain photos" },
    { id: "125", name: "myphotopack", url: "https://myphotopack.com", desc: "A free photo pack just for you. Every month." },
    { id: "140", name: "jeshoots", url: "http://jeshoots.com", desc: "New Free Photos & Mockups in to your Inbox!" },
    { id: "118", name: "Unsplash", url: "https://unsplash.com", desc: "Beautiful, free photos." },
    { id: "126", name: "Notaselfie", url: "http://notaselfie.com", desc: "Photos that happen along the way. You can use the images anyway you like. Have fun!" },
  ],
  "iOS捷径": [
    { id: "970", name: "快捷指令库", url: "https://www.rcuts.com", desc: "快捷指令库（rcuts.com）专注分享苹果手机iOS快捷指令大全，提供实用的iPhone快捷指令下载与教程，快捷指令又名iOS捷径，是苹果为iPhone及iPad推出的一款效率工具。" },
    { id: "975", name: "少数派", url: "https://sspai.com/page/playbook/zh-CN", desc: "少数派致力于更好地运用数字产品或科学方法，帮助用户提升工作效率和生活品质" },
    { id: "969", name: "捷径指令大全分享频道", url: "https://t.me/qingtianwe", desc: "" },
    { id: "972", name: "ShortcutsGallery.com", url: "https://shortcutsgallery.com", desc: "Download powerful Siri Shortcuts from others or share the ones you created with the world. These shortcuts will boost your iOS experience." },
    { id: "976", name: "爱捷径", url: "https://www.ijiejing.com", desc: "爱捷径是一个分享苹果快捷指令规则的网站。快捷指令又名iOS捷径，是苹果为iPhone及iPad推出的一款效率工具。可以帮助你高效地完成各种任务。爱捷径收集了许多实用和创新的快捷指令，你可以在这里发现最新的功能和构建技巧。只需在捷径库中点击“获取捷径”，即可将你喜欢的快捷指令添加到你的iOS设备上使用。" },
    { id: "968", name: "捷径库", url: "https://jiejingku.net", desc: "捷径库是苹果快捷指令规则的分享网站。快捷指令是Apple官方出品的iPhone内置效率应用，通过快捷指令可以快捷高效的完成多项任务。捷径库精选了一系列富有创意且实用的快捷指令，探索捷径库可获取快捷指令的最新功能和构建方式。在捷径库中轻点「获取捷径」即可将快捷指令添加到iOS设备中使用。" },
    { id: "966", name: "柯基捷径库", url: "https://www.kejicut.com", desc: "柯基捷径库（www.kejicut.com）专注分享苹果iOS快捷指令与教程,提供高质量iOS捷径,快捷指令原名workflow又名捷径,苹果生态iPhone/iPad/Mac中的一款效率软件。" },
    { id: "977", name: "快捷指令合集", url: "https://hejicut.com", desc: "快捷指令合集（hejicut.com）专注分享iOS快捷指令规则。" },
    { id: "973", name: "实况捷径", url: "https://jiejing.fun", desc: "实况捷径 - 一键转换网络内容和本地媒体为 Live Photo 实况图" },
    { id: "965", name: "iPhone 吧", url: "https://iphone8.vip", desc: "小良,捷径,规则,脚本,解析,应用,教程,下载,快捷指令,Shortcuts,pin脚本,jsbox脚本" },
    { id: "974", name: "奇迹秀", url: "https://www.qijishow.com/Brand/Brand69/index.html", desc: "奇迹秀是一个公益组织，为设计师提供设计干货及资源，站内所有收集的资源都能免费下载，且资源都经过组织成员测试后再发布，保证资源绿色，大家可放心使用，" },
    { id: "967", name: "ShortcutsGallery.com", url: "https://shortcutsgallery.com", desc: "Download powerful Siri Shortcuts from others or share the ones you created with the world. These shortcuts will boost your iOS experience." },
    { id: "964", name: "MacStories", url: "https://www.macstories.net/shortcuts", desc: "Apple news, app reviews, and stories by Federico Viticci and friends." },
    { id: "971", name: "Archive", url: "https://sharecuts.app", desc: "A collection of shortcuts for iOS." },
  ],
  "IOS签名工具": [
    { id: "979", name: "万能签", url: "https://sign.wnqapp.com/ios/indexes.php", desc: "万能签 最新版本7.9.1 大小5.85MB 适用于iOS12以上所有iPhone/iPad。应用信息：一款适用于iOS端IPA的签名注入开发调试工具，所有功能完全免费。支持一键签署多开APP，一键注入移除动态库等，可脱离联网使用，在线安装无需电脑，严禁签名外挂应用及违规APP。" },
    { id: "978", name: "全能签", url: "https://udid.nuosike.cn/sign", desc: "诺思客越狱工具定制签名在线安装" },
    { id: "982", name: "牛蛙助手", url: "https://ios222.com", desc: "牛蛙助手官网-牛蛙助手是一款专业的ios移动端必备的工具，牛蛙助手免费为苹果用户提供：ios移动端免越狱使用apple id签名，ios移动端免越狱全局修改gps定位信息,牛蛙,牛蛙助手,ios222,牛蛙神器" },
    { id: "980", name: "NB全能助手", url: "https://nbtool8.com", desc: "NB全能助手(原NB助手)" },
    { id: "988", name: "TrollStore 2", url: "https://trollstore.app", desc: "TrollStore 2 in a permasigned jailed app that can permanently install any IPA you open in it." },
    { id: "981", name: "爱思助手", url: "https://www.i4.cn", desc: "爱思助手官网-爱思助手是一款专业的苹果刷机助手、苹果越狱助手，专为苹果用户提供百万iPhone、iPad软件、游戏、铃声、壁纸资源安全快速免费下载。" },
    { id: "985", name: "Sideloadly", url: "https://sideloadly.io", desc: "Sideloadly is a tool for sideloading apps on iOS, Apple Silicon Macs, and Apple TV without jailbreak. Download now for a secure and easy sideloading experience." },
    { id: "983", name: "PlayCover", url: "https://playcover.io", desc: "PlayCover allows you to run iOS apps and games natively with keymapping on your Apple Silicon Mac!" },
    { id: "987", name: "GBox", url: "https://gbox.run", desc: "GBox is a professional iOS signing and testing tool, supporting systems from iOS 12.0 to 26. It offers functions such as IPA resigning and app installation testing, allowing you to complete the signing and installation process without the need for a computer. It also supports installation via TrollStore." },
  ],
  "iOS网站": [
    { id: "1023", name: "苹果软件库", url: "https://ios.cuiun.cc/app", desc: "苹果AppStore付费游戏应用共享，致力于分享 iOS 付费软件资源下载和分享，包括游戏共享 ID、软件应用共享 ID等资源的分享和下载，做最稳定最优秀的 iOS 付费游戏/软件共享网站。" },
    { id: "1026", name: "十三资源库", url: "https://tool.joia.cn", desc: "十三资源库，专属于果粉的工具箱. From JoiHouse钟意小屋" },
    { id: "1028", name: "吾爱苹果账号网", url: "https://www.52appleid.com", desc: "为大家分享苹果iOS付费游戏、应用已购账号,免费分享最新的外区苹果共享账号,主要有美国、日本、韩国、香港、台湾地区等海外Apple ID免费分享!" },
    { id: "1029", name: "APPID免费分享", url: "https://appdb.to", desc: "Independent marketplace for iOS, iPadOS, MacOS, Apple devices. Publish your apps for free independently. Install apps that you want securely and privately. - appdb" },
    { id: "1027", name: "林先生苹果工具箱", url: "https://lin.mrlin.vip", desc: "林先生苹果工具箱" },
    { id: "1018", name: "神科技工具页", url: "https://ai.id64.com/index.aspx", desc: "" },
    { id: "1015", name: "挂神团队", url: "https://app.nk8686.com", desc: "挂神团队" },
    { id: "1016", name: "威锋", url: "https://www.feng.com", desc: "威锋，千万果粉大本营，是中文苹果用户首选的苹果媒体及苹果社区。来威锋，看苹果资讯、讨论当下科技热点、分享玩机心得、优惠购买苹果产品、参与科技酷品试玩活动，获得更多苹果服务。威锋提供7*24小时的苹果资讯，科技原创观点、Apple软硬件、智能硬件评测等，涵盖Apple的iPhone、Mac、iPad、Apple Watch等全系列产品及周边。威锋社区犹如宝藏，沉淀了几亿个关于苹果系统（macOS、iOS）、插件软件壁纸游戏资源、玩机技巧、开箱晒货、摄影、配件硬件等与苹果科技相关的分享讨论。" },
    { id: "1000", name: "玄烨品果", url: "https://dkxuanye.cn", desc: "" },
    { id: "1013", name: "异次元软件世界", url: "https://www.iplaysoft.com/os/ios-platform", desc: "极具人气和特色的软件网站！专注于推荐优秀软件、APP应用和互联网资源，每篇图文评测都极其用心，并提供大量软件资源下载。" },
    { id: "1011", name: "蘋果iPhone", url: "https://mrmad.com.tw", desc: "提供最新蘋果、iPhone、iPad、Apple Watch、Mac和3C科技資訊，以專業經驗免費與大家分享。" },
    { id: "1032", name: "Decrypt IPA Store", url: "https://decrypt.day", desc: "Just a moment..." },
    { id: "1019", name: "微信美化", url: "https://soda-ldz.yourepo.com", desc: "" },
    { id: "1030", name: "玩机大学", url: "https://www.cccitu.com/cat/ios", desc: "CCCiTU 玩机大学 - 只玩干货教程" },
    { id: "1025", name: "misaka", url: "https://github.com/straight-tamago/misaka", desc: "" },
    { id: "1022", name: "Apple (中国大陆)", url: "https://www.apple.com.cn", desc: "探索 Apple 的创新世界，选购各式 iPhone、iPad、Apple Watch 和 Mac，浏览各类配件、娱乐产品，并获得相关产品的专家服务支持。" },
    { id: "1003", name: "苹果系统固件查询与下载", url: "https://ipsw.me", desc: "Download current and previous versions of Apple's iOS, iPadOS, watchOS, tvOS, audioOS and macOS firmware and receive notifications when new firmwares are released." },
    { id: "999", name: "TutuApp VIP", url: "https://github.com/opa334/Dopamine", desc: "Join the world's most widely adopted, AI-powered developer platform where millions of developers, businesses, and the largest open source community build software that advances humanity." },
    { id: "1020", name: "越狱论坛", url: "https://whyjailbreak.com", desc: "" },
    { id: "1021", name: "依赖查询网址", url: "https://www.ios-repo-updates.com", desc: "Cydia iOS Repository Updates for Jailbroken iPhone iPad or iPod" },
  ],
  "Chrome插件": [
    { id: "189", name: "wappalyzer", url: "https://www.wappalyzer.com", desc: "Identify technology on websites" },
    { id: "192", name: "csspeeper", url: "https://csspeeper.com", desc: "Smart CSS viewer tailored for Designers." },
    { id: "190", name: "Panda", url: "http://usepanda.com", desc: "A smart news reader built for productivity." },
    { id: "191", name: "sizzy", url: "https://sizzy.co", desc: "overflowClip_2\">A tool for developing responsive websites crazy-fast" },
    { id: "194", name: "mustsee", url: "http://mustsee.earth", desc: "Discover the world's most beautiful places at every opened tab." },
  ],
  "交互动效": [
    { id: "162", name: "Adobe After Effects CC", url: "https://www.adobe.com/cn/products/aftereffects", desc: "电影般的视觉效果和动态图形。" },
    { id: "163", name: "principle", url: "http://principleformac.com", desc: "Animate Your Ideas, Design Better Apps" },
    { id: "164", name: "flinto", url: "https://www.flinto.com", desc: "Flinto is a Mac app used by top designers around the world to create interactive and animated prototypes of their app designs." },
    { id: "166", name: "ProtoPie", url: "http://www.protopie.cn", desc: "高保真交互原型设计" },
    { id: "165", name: "framer", url: "https://framer.com", desc: "Design everything from detailed icons to high-fidelity interactions—all in one place." },
  ],
  "图形创意": [
    { id: "150", name: "Affinity Designer", url: "https://affinity.serif.com", desc: "专业创意软件" },
    { id: "149", name: "photoshop", url: "https://www.adobe.com/cn/products/photoshop.html", desc: "Photoshop不需要解释" },
    { id: "155", name: "Blender", url: "https://www.blender.org", desc: "Blender is the free and open source 3D creation suite." },
    { id: "151", name: "Illustrator", url: "https://www.adobe.com/cn/products/illustrator", desc: "矢量图形和插图。" },
    { id: "152", name: "indesign", url: "http://www.adobe.com/cn/products/indesign.html", desc: "页面设计、布局和出版。" },
    { id: "154", name: "3ds-max", url: "https://www.autodesk.com/products/3ds-max/overview", desc: "3D modeling, animation, and rendering software" },
    { id: "153", name: "cinema-4d", url: "https://www.maxon.net/en/products/cinema-4d/overview", desc: "Cinema 4D is the perfect package for all 3D artists who want to achieve breathtaking results fast and hassle-free." },
  ],
  "在线工具": [
    { id: "188", name: "稿定抠图", url: "https://www.gaoding.com", desc: "免费在线抠图软件,图片快速换背景-抠白底图" },
    { id: "183", name: "goqr", url: "http://goqr.me", desc: "create QR codes for free (Logo, T-Shirt, vCard, EPS)" },
    { id: "184", name: "ezgif", url: "https://ezgif.com", desc: "simple online GIF maker and toolset for basic animated GIF editing." },
    { id: "186", name: "screen sizes", url: "http://screensiz.es", desc: "Viewport Sizes and Pixel Densities for Popular Devices" },
    { id: "185", name: "Android 9 patch", url: "http://inloop.github.io/shadow4android", desc: "Android 9-patch shadow generator fully customizable shadows" },
    { id: "187", name: "svgomg", url: "https://jakearchibald.github.io/svgomg", desc: "SVG在线压缩平台" },
    { id: "182", name: "tinypng", url: "https://tinypng.com", desc: "Optimize your images with a perfect balance in quality and file size." },
  ],
  "界面设计": [
    { id: "161", name: "figma", url: "https://www.figma.com", desc: "Design, prototype, and gather feedback all in one place with Figma." },
    { id: "160", name: "Muse CC", url: "https://creative.adobe.com/zh-cn/products/download/muse", desc: "无需利用编码即可进行网站设计。" },
    { id: "158", name: "invisionapp", url: "https://www.invisionapp.com", desc: "Powerful design prototyping tools" },
    { id: "159", name: "marvelapp", url: "https://marvelapp.com", desc: "Simple design, prototyping and collaboration" },
    { id: "157", name: "Adobe XD", url: "http://www.adobe.com/products/xd.html", desc: "Introducing Adobe XD. Design. Prototype. Experience." },
    { id: "156", name: "Sketch", url: "https://sketchapp.com", desc: "The digital design toolkit" },
  ],
  "LOGO设计": [
    { id: "61", name: "World Vector Logo", url: "https://worldvectorlogo.com", desc: "Brand logos free to download" },
    { id: "62", name: "Instant Logo Search", url: "http://instantlogosearch.com", desc: "Search & download thousands of logos instantly" },
    { id: "60", name: "iOS Icon Gallery", url: "http://iosicongallery.com", desc: "Showcasing beautiful icon designs from the iOS App Store" },
    { id: "58", name: "Iconsfeed", url: "http://www.iconsfeed.com", desc: "Looking for iOS icon inspiration? We bring the iOS icons gallery to you." },
  ],
  "Mockup": [
    { id: "113", name: "Threed", url: "http://threed.io", desc: "Generate 3D Mockups right in your Browser" },
    { id: "111", name: "Dunnnk", url: "http://dunnnk.com", desc: "Generate Product Mockups For Free" },
    { id: "110", name: "MockupZone", url: "https://mockup.zone", desc: "Mockup Zone is an online store where you can find free and premium PSD mockup files to show your designs in a professional way." },
    { id: "114", name: "Mockup World", url: "https://free.lstore.graphics", desc: "The best free Mockups from the Web" },
    { id: "112", name: "Graphberry", url: "http://www.graphberry.com", desc: "Free design resources, Mockups, PSD web templates, Icons" },
    { id: "117", name: "For Graphic TM", url: "http://forgraphictm.com", desc: "High Quality PSD Mockups for Graphic Designers." },
    { id: "116", name: "pixeden", url: "https://www.pixeden.com", desc: "free web resources and graphic design templates." },
    { id: "115", name: "Lstore", url: "https://free.lstore.graphics", desc: "Exclusive mindblowing freebies for designers and developers" },
  ],
  "PPT资源": [
    { id: "143", name: "OfficePLUS", url: "http://www.officeplus.cn/Template/Home.shtml", desc: "OfficePLUS，微软Office官方在线模板网站！" },
    { id: "148", name: "5百丁", url: "http://ppt.500d.me", desc: "中国领先的PPT模板共享平台" },
    { id: "144", name: "优品PPT", url: "http://www.ypppt.com", desc: "高质量的模版，而且还有PPT图表，PPT背景图等资源" },
    { id: "145", name: "PPT+", url: "http://www.pptplus.cn", desc: "PPT加直播、录制和分享—PPT+语音内容分享平台" },
    { id: "146", name: "PPTMind", url: "http://www.pptmind.com", desc: "分享高端ppt模板与keynote模板的数字作品交易平台" },
    { id: "147", name: "tretars", url: "http://www.tretars.com/ppt-templates", desc: "The best free Mockups from the Web" },
  ],
  "Sketch资源": [
    { id: "91", name: "Sketch中文网", url: "http://www.sketchcn.com", desc: "分享最新的Sketch中文手册" },
    { id: "87", name: "Sketch Measure", url: "http://utom.design/measure", desc: "Friendly user interface offers you a more intuitive way of making marks." },
    { id: "88", name: "Sketch App Sources", url: "https://www.sketchappsources.com", desc: "Free design resources and plugins - Icons, UI Kits, Wireframes, iOS, Android Templates for Sketch" },
    { id: "94", name: "Sketchcasts", url: "https://www.sketchcasts.net", desc: "Learn Sketch Train your design skills with a weekly video tutorial" },
    { id: "90", name: "Sketch Hunt", url: "http://sketchhunt.com", desc: "Sketch Hunt is an independent blog sharing gems in learning, plugins & design tools for fans of Sketch app." },
    { id: "86", name: "Sketch", url: "https://sketchapp.com", desc: "The digital design toolkit" },
    { id: "93", name: "Awesome Sketch Plugins", url: "https://awesome-sket.ch", desc: "A collection of really useful Sketch plugins." },
  ],
  "图标素材": [
    { id: "55", name: "Font Awesome Icon", url: "https://fontawesome.com/icons", desc: "The complete set of 675 icons in Font Awesome" },
    { id: "57", name: "Simpleline Icons", url: "http://simplelineicons.com", desc: "Simple line Icons pack" },
    { id: "53", name: "UICloud", url: "http://ui-cloud.com", desc: "The largest user interface design database in the world." },
    { id: "54", name: "Material icons", url: "https://material.io/icons", desc: "Access over 900 material system icons, available in a variety of sizes and densities, and as a web font." },
    { id: "48", name: "Icon Archive", url: "http://www.iconarchive.com", desc: "Search 590,912 free icons" },
    { id: "50", name: "IcoMoonApp", url: "https://icomoon.io/app", desc: "Icon Font, SVG, PDF & PNG Generator" },
    { id: "51", name: "easyicon", url: "http://www.easyicon.net", desc: "PNG、ICO、ICNS格式图标搜索、图标下载服务" },
    { id: "46", name: "iconfont", url: "http://www.iconfont.cn", desc: "阿里巴巴矢量图标库" },
    { id: "52", name: "flaticon", url: "https://www.flaticon.com", desc: "634,000+ Free vector icons in SVG, PSD, PNG, EPS format or as ICON FONT." },
    { id: "45", name: "Iconfinder", url: "https://www.iconfinder.com", desc: "2,100,000+ free and premium vector icons." },
    { id: "47", name: "iconmonstr", url: "https://iconmonstr.com", desc: "Free simple icons for your next project" },
    { id: "49", name: "FindIcons", url: "https://findicons.com", desc: "Search through 300,000 free icons" },
  ],
  "UI资源": [
    { id: "9", name: "UI中国", url: "http://www.ui.cn", desc: "图形交互与界面设计交流、作品展示、学习平台。" },
    { id: "240", name: "UI自用导航", url: "http://dh.simple.red", desc: "UI设计师自用导航" },
    { id: "79", name: "Designmodo", url: "https://designmodo.com", desc: "Web Design Blog and Shop" },
    { id: "80", name: "稀土区", url: "https://xituqu.com", desc: "优质设计开发资源分享" },
    { id: "76", name: "Freebiesbug", url: "https://freebiesbug.com", desc: "Hand-picked resources for web designer and developers, constantly updated." },
    { id: "78", name: "云瑞", url: "https://www.yrucd.com", desc: "优秀设计资源的分享网站" },
    { id: "83", name: "UIkit.me", url: "http://www.uikit.me", desc: "最便捷新鲜的uikit资源下载网站" },
    { id: "77", name: "Freebie Supply", url: "https://freebiesupply.com", desc: "Free Resources For Designers" },
    { id: "85", name: "PrincipleRepo", url: "http://principlerepo.com", desc: "Free, High Quality Principle Resources" },
    { id: "82", name: "uplabs", url: "https://www.uplabs.com", desc: "Daily resources for product designers & developers" },
    { id: "84", name: "Fribbble", url: "http://www.fribbble.com", desc: "Free PSD files and other free design resources by Dribbblers." },
    { id: "81", name: "ui8", url: "https://ui8.net", desc: "UI Kits, Wireframe Kits, Templates, Icons and More" },
  ],
  "字体资源": [
    { id: "103", name: "FONTS2U", url: "https://fonts2u.com", desc: "Download free fonts for Windows and Macintosh." },
    { id: "96", name: "Typekit", url: "https://typekit.com", desc: "Quality fonts from the world’s best foundries." },
    { id: "98", name: "字体传奇网", url: "http://ziticq.com", desc: "中国首个字体品牌设计师交流网" },
    { id: "104", name: "Fontex", url: "http://www.fontex.org", desc: "Free Fonts to Download + Premium Typefaces" },
    { id: "101", name: "Urban Fonts", url: "https://www.urbanfonts.com", desc: "Download Free Fonts and Free Dingbats." },
    { id: "97", name: "方正字库", url: "http://www.foundertype.com", desc: "方正字库官方网站" },
    { id: "56", name: "ion icons", url: "http://ionicons.com", desc: "The premium icon font for Ionic Framework" },
    { id: "99", name: "私藏字体", url: "http://sicangziti.com", desc: "优质字体免费下载站" },
    { id: "107", name: "Da Font", url: "https://www.dafont.com", desc: "Archive of freely downloadable fonts." },
    { id: "95", name: "Google Font", url: "https://fonts.google.com", desc: "Making the web more beautiful, fast, and open through great typography" },
    { id: "109", name: "Abstract Fonts", url: "http://www.abstractfonts.com", desc: "Abstract Fonts (13,866 free fonts)" },
    { id: "102", name: "Lost Type", url: "http://www.losttype.com", desc: "Lost Type is a Collaborative Digital Type Foundry" },
    { id: "100", name: "Fontsquirrel", url: "https://www.fontsquirrel.com", desc: "FREE fonts for graphic designers" },
    { id: "105", name: "FontM", url: "http://fontm.com", desc: "Free Fonts" },
    { id: "106", name: "My Fonts", url: "http://www.myfonts.com", desc: "Fonts for Print, Products & Screens" },
    { id: "108", name: "OnlineWebFonts", url: "https://www.onlinewebfonts.com", desc: "WEB Free Fonts for Windows and Mac / Font free Download" },
  ],
  "其他网盘": [
    { id: "952", name: "梓澪の妙妙屋", url: "https://zi0.cc", desc: "梓澪の妙妙屋 | 免费Galgame仓库&下载站" },
    { id: "958", name: "洋芋资源站", url: "https://pan.51yangyu.cn", desc: "洋芋资源站" },
    { id: "955", name: "萤火虫资源站", url: "https://www.yhcres.top", desc: "" },
    { id: "962", name: "小乐的网盘", url: "https://share.xiaole88.com", desc: "小乐的网盘" },
    { id: "950", name: "七十二时.的资源站", url: "https://alist.qsesvick.top", desc: "七十二时.的资源站" },
    { id: "949", name: "七米蓝的仓库", url: "https://al.chirmyram.com", desc: "OpenList" },
    { id: "951", name: "亿苯正经的OpenList库", url: "https://pan.lm379.cn", desc: "lm379" },
    { id: "960", name: "布满灰尘的仓库", url: "https://pan.baiblog.ren", desc: "布满灰尘的仓库" },
    { id: "954", name: "AI Hobbyist 资源库", url: "https://res.acgnai.top", desc: "AI Hobbyist 资源库" },
    { id: "1118", name: "雨云资源镜像站", url: "https://mirrors.rainyun.com", desc: "雨云资源镜像站" },
    { id: "957", name: "MOAPYR 资源站", url: "https://www.moapyr.com", desc: "MOAPYR 资源站" },
    { id: "956", name: "小爱音箱资源站", url: "https://xiaoai.qgmzmy.me", desc: "小爱音箱资源站" },
    { id: "959", name: "GistWillian的资源网盘", url: "https://share.gistwillan.top", desc: "GistWillian的资源网盘" },
    { id: "953", name: "Azad", url: "https://alist.azad.asia", desc: "Azad - 个人云盘" },
    { id: "961", name: "Pengcheng", url: "https://pan.pengcheng.team", desc: "Pengcheng's Download" },
  ],
  "AI工具": [
    { id: "1099", name: "chatgpt", url: "https://chatgpt.com", desc: "Attention Required! | Cloudflare" },
    { id: "1093", name: "1Chat.vin", url: "https://chat03.a1r.cc/#/chat/1002", desc: "1Chat.vin国内免费且最快的智能AI" },
    { id: "1096", name: "通义", url: "https://tongyi.aliyun.com/qianwen", desc: "" },
    { id: "1084", name: "文心一言", url: "https://yiyan.baidu.com/agreement", desc: "" },
    { id: "1085", name: "豆包", url: "https://www.doubao.com/chat", desc: "" },
    { id: "1102", name: "AI Code Reviews", url: "https://bito.ai", desc: "AI Code Reviews designed for modern dev teams. Cut review time, improve code quality, and ship with confidence — with contextual, senior-level feedback." },
    { id: "1083", name: "DeepSeek", url: "https://chat.deepseek.com", desc: "Chat with DeepSeek AI – your intelligent assistant for coding, content creation, file reading, and more. Upload documents, engage in long-context conversations, and get expert help in AI, natural language processing, and beyond. | 深度求索（DeepSeek）助力编程代码开发、创意写作、文件处理等任务，支持文件上传及长文本对话，随时为您提供高效的AI支持。" },
    { id: "1086", name: "腾讯混元", url: "https://hunyuan.tencent.com", desc: "" },
    { id: "1097", name: "讯飞星火", url: "https://xinghuo.xfyun.cn/desk?ch=xhweb_sax", desc: "讯飞星火大模型，是由科大讯飞推出的新一代认知智能大模型，拥有跨领域的知识和语言理解能力，能够基于自然对话方式理解与执行任务，提供语言理解、知识问答、逻辑推理、数学题解答、代码理解与编写等多种能力。" },
    { id: "1094", name: "欢迎来到AI的世界", url: "https://vip8.1ai.ink/chat?t12/?t12", desc: "欢迎来到AI的世界" },
    { id: "1095", name: "Kimi", url: "https://kimi.moonshot.cn", desc: "Kimi K2 是我们最新升级的 AI 助手，擅长推理、编程和调用工具，帮助你高效解决复杂问题。无论是工作、学习还是创作，都可以试试用 Kimi K2 来完成。" },
    { id: "1100", name: "秘塔写作猫", url: "https://xiezuocat.com", desc: "秘塔写作猫" },
    { id: "1090", name: "智谱清言", url: "https://chatglm.cn/main/guest?lang=zh", desc: "" },
    { id: "1101", name: "智谱AI开放平台", url: "https://www.bigmodel.cn/login", desc: "智谱大模型开放平台-新一代国产自主通用AI大模型开放平台，是国内大模型排名前列的大模型网站，研发了多款LLM模型，多模态视觉模型产品，致力于将AI产品技术与行业场景双轮驱动的中国先进的认知智能技术和千行百业应用相结合，构建更高精度、高效率、通用化的AI开发新模式和企业级解决方案，实现智谱大模型的产业化，将AI的好处带给每个人。" },
    { id: "1092", name: "AI问答宝", url: "https://ai.wendabao-d.net/#/chat/1738810429887", desc: "免费人工智能在线对话问答，免费在线AI论文写作、绘图，免费ChatGPT Plus" },
    { id: "1089", name: "360 AI", url: "https://ai.360.cn", desc: "360安全云" },
    { id: "1091", name: "AI办公智能体先行者", url: "https://www.tiangong.cn", desc: "天工Skywork是一款具备超强DeepResearch能力的全新AI Office智能体，通过3个专家agent和1个通用agent，让AI深度研究，一键生成AI文档、AI PPT、AI表格，高效应对各类办公、学习场景；也支持网页html、图像、视频、有声书、绘本等多种形式的创意内容创作，激发无限灵感。 天工Skywork融合先进的多模态理解与深度检索分析技术，一问即得科研级、专业级、咨询级的高质量结果，帮助你摆脱繁琐事务，显著提升效率。 无论你是职场白领、科研人员、大学生、研究生，还是自媒体KOL，天工Skywork都将是你值得信赖的智能伙伴，助你专注思考、释放创造力。" },
    { id: "1088", name: "鱼聪明AI", url: "https://www.yucongming.com/?current=1", desc: "" },
    { id: "1103", name: "Kodezi", url: "https://kodezi.com", desc: "Kodezi is your AI CTO—an autonomous operating system that maintains, evolves, and governs modern codebases. Seamlessly integrated across your stack, it ensures your software remains healthy, scalable, and always ready to ship." },
    { id: "1087", name: "百小应", url: "https://ying.baichuan-ai.com/chat", desc: "查指南、找文献、搜药品，每一条医学建议都有据可依！" },
  ],
  "网盘云储": [
    { id: "863", name: "百度网盘", url: "https://pan.baidu.com", desc: "百度网盘是一款国民级产品" },
    { id: "870", name: "阿里云盘", url: "https://www.aliyundrive.com", desc: "阿里云盘是一款速度快的个人网盘" },
    { id: "871", name: "115网盘", url: "https://115.com", desc: "115，一生相伴" },
    { id: "868", name: "Google云盘", url: "https://www.google.com/drive", desc: "轻松安全地访问您的所有内容" },
    { id: "869", name: "天翼云盘", url: "https://cloud.189.cn/web/login.html", desc: "珍藏美好生活 家庭云" },
    { id: "864", name: "盘它云网盘", url: "https://pantayun.com/invite/?code=S6OgV3", desc: "盘它云网盘是向广大用户提供上传空间和技术的信息存储空间服务平台。" },
    { id: "865", name: "边乐云网盘", url: "https://yun.bianyue.cn", desc: "边乐云网盘致力于为用户提供安全稳定的云存储产品" },
    { id: "866", name: "OneDrive", url: "https://onedrive.live.com", desc: "Store photos and docs online. Access them from any PC, Mac or phone. Create and work together on Word, Excel or PowerPoint documents." },
    { id: "867", name: "微云", url: "https://www.weiyun.com", desc: "微云是腾讯公司为用户精心打造的一项智能云服务" },
  ],
  "购物网站": [
    { id: "1080", name: "免费领流量卡", url: "https://h5.lot-ml.com/ProductEn/Index/03607e34ea182d64", desc: "", icon: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZlcnNpb249IjEuMSIgd2lkdGg9IjEwMCIgaGVpZ2h0PSIxMDAiPg0KICAgICAgICAgICAgICAgIDxyZWN0IGZpbGw9InJnYigyMjksMTM3LDE0OCkiIHg9IjAiIHk9IjAiIHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIj48L3JlY3Q+DQogICAgICAgICAgICAgICAgPGNpcmNsZSBmaWxsPSJyZ2IoMjI5LDExNCwyMTQpIiBjeD0iMjMiIGN5PSIxMS41IiByPSI2MCIgIG9wYWNpdHk9Ii40Ij48L2NpcmNsZT4NCiAgICAgICAgICAgICAgICA8Y2lyY2xlIGZpbGw9InJnYigyMjksMTg3LDExNCkiIGN4PSI5MyIgY3k9IjE4NiIgcj0iNTAiICBvcGFjaXR5PSIuNiI+PC9jaXJjbGU+DQogICAgICAgICAgICAgICAgPHRleHQgeD0iNTAiIHk9IjUwIiBmb250LXNpemU9IjUwIiB0ZXh0LWNvcHk9ImZhc3QiIGZpbGw9IiNmZmZmZmYiIHRleHQtYW5jaG9yPSJtaWRkbGUiIHRleHQtcmlnaHRzPSJhZG1pbiIgYWxpZ25tZW50LWJhc2VsaW5lPSJjZW50cmFsIiBmb250LWZhbWlseT0iJ1BpbmdGYW5nIFNDJywnTWljcm9zb2Z0IFlhaGVpJyI+5YWNPC90ZXh0Pjwvc3ZnPg==" },
    { id: "1105", name: "苹果证书", url: "https://puaaa.cn/shop/10.html", desc: "稳定的苹果证书！", icon: "https://puaaa.cn/wp-content/uploads/2026/05/bluesky.svg" },
    { id: "1140", name: "聚浪科技", url: "http://www.jlqc.top", desc: "" },
  ],
  "社区资讯": [
    { id: "18", name: "数英网", url: "https://www.digitaling.com", desc: "数字媒体及职业招聘网站" },
    { id: "738", name: "WordPress大学", url: "https://www.wpdaxue.com", desc: "WordPress大学专注于wordpress建站教学,提供wordpress主题,wordpres" },
    { id: "21", name: "优阁网", url: "http://www.uigreat.com", desc: "UI设计师学习交流社区" },
    { id: "16", name: "雷锋网", url: "https://www.leiphone.com", desc: "人工智能和智能硬件领域的互联网科技媒体" },
    { id: "19", name: "猎云网", url: "http://www.lieyunwang.com", desc: "互联网创业项目推荐和创业创新资讯" },
    { id: "248", name: "站长资讯平台", url: "http://www.1994july.club", desc: "站长资讯平台为个人站长与企业网络提供全面的站长资讯，一站式网络解决方案，我们一直致力为中文网站提供动" },
    { id: "20", name: "产品壹佰", url: "http://www.chanpin100.com", desc: "为产品经理爱好者提供最优质的产品资讯、原创内容和相关视频课程" },
    { id: "17", name: "36kr", url: "http://36kr.com", desc: "创业资讯、科技新闻" },
  ],
  "UED团队": [
    { id: "200", name: "腾讯CDC", url: "http://cdc.tencent.com", desc: "腾讯CDC关注于互联网视觉设计、交互设计、用户研究、前端开发。" },
    { id: "208", name: "京东设计中心", url: "http://jdc.jd.com", desc: "京东设计中心" },
    { id: "198", name: "eico design", url: "http://eicodesign.com", desc: "数字化咨询与产品专家" },
    { id: "201", name: "TGideas", url: "http://tgideas.qq.com", desc: "TGideas隶属于腾讯公司互动娱乐业务系统的专业推广类设计团队" },
    { id: "202", name: "ISUX", url: "https://isux.tencent.com", desc: "腾讯社交用户体验设计部" },
    { id: "197", name: "Google Design", url: "https://design.google", desc: "Google Design" },
    { id: "205", name: "U一点", url: "http://www.aliued.cn", desc: "阿里巴巴（中国站）用户体验设计部博客U一点设计 UED团队" },
    { id: "209", name: "百度企业产品用户体验中心", url: "http://eux.baidu.com", desc: "百度企业产品用户体验中心" },
    { id: "196", name: "Facebook Design", url: "http://facebook.design", desc: "Facebook Design" },
    { id: "388", name: "WordPress主题君", url: "https://www.ztjun.com", desc: "精选免费WordPress主题模板下载", icon: "https://nav.iowen.cn/wp-content/uploads/2020/03/20200305153742_fc6e5c59.png" },
    { id: "210", name: "携程设计委员会", url: "http://ued.ctrip.com", desc: "携程设计委员会-Ctrip Design Committee" },
    { id: "199", name: "nice design", url: "http://www.niceui.cn", desc: "nicedesign奈思设计是领先的用户体验设计与互联网品牌建设公司" },
    { id: "207", name: "百度用户体验中心", url: "http://ued.baidu.com", desc: "百度用户体验中心" },
    { id: "195", name: "Airbnb Design", url: "https://airbnb.design", desc: "Airbnb Design" },
  ],
};

export const navGroups: NavGroup[] = [{"id": "ios", "name": "iOS资源", "icon": "📱", "desc": "iOS网盘 / 捷径 / 签名工具 / 网站 / TG资源", "cats": ["iOS网盘", "iOS捷径", "IOS签名工具", "iOS网站", "TG资源"]}, {"id": "other-pan", "name": "其他网盘", "icon": "📦", "desc": "Galgame仓库与个人资源分享网盘", "cats": ["其他网盘"]}, {"id": "ai", "name": "AI工具", "icon": "🤖", "desc": "ChatGPT、豆包、DeepSeek 等主流 AI 助手", "cats": ["AI工具"]}, {"id": "cloud", "name": "网盘云储", "icon": "☁️", "desc": "百度网盘、阿里云盘等云存储服务", "cats": ["网盘云储"]}, {"id": "shop", "name": "购物网站", "icon": "🛒", "desc": "流量卡、证书等实用购物站点", "cats": ["购物网站"]}, {"id": "news", "name": "社区资讯", "icon": "📰", "desc": "互联网科技媒体与设计师社区", "cats": ["社区资讯"]}, {"id": "tools", "name": "常用工具", "icon": "🧰", "desc": "在线配色 / 插件 / 动效 / 在线工具", "cats": ["在线配色", "Chrome插件", "交互动效", "图形创意", "在线工具", "界面设计"]}, {"id": "assets", "name": "素材资源", "icon": "🎨", "desc": "平面素材 / LOGO / Mockup / PPT 等", "cats": ["平面素材", "LOGO设计", "Mockup", "PPT资源", "Sketch资源", "图标素材", "UI资源", "字体资源", "摄影图库"]}, {"id": "ued", "name": "UED团队", "icon": "👥", "desc": "腾讯、京东、Google 等大厂设计团队", "cats": ["UED团队"]}];
